[JDBC 라이브러리 구현하기 - 1단계] 페퍼(최수연) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #102
Opened 2022-10-03 11:40 UTC by SuyeonChoi

안녕하세요 디우!
왜이리 오랜만인거죠,,,🥲 이렇게 코드리뷰로 다시 만나게 되어서 정말 반갑네요,,🌟🌟

이번 미션에서는 1단계 기능 요구사항에 맞춰 JdbcTemplate 라이브러리를 만들고, 이를 app 모듈에서 사용할 수 있도록 변경하였습니다.
현재 컨트롤러의 책임이 매우 의심되지만, 1단계 체크리스트에서는 따로 명시하지 않아 app 모듈 내의 코드 변경은 최소화하였어요. 
2단계가 리팩터링인 만큼 그때 해도 된다고 생각했고, 디우 리뷰어님이 리뷰로 남겨준다면 함께 개선해나가고 싶습니다🙇‍♀️🙇‍♀️

데이터의 저장을 `InMemoryUserRepository`가 아닌 H2에 저장하도록 변경했는데요. 
결국 in-memory DB라서 `UserDaoTest`의 각 테스트마다 데이터가 롤백되지 않아 유저 정보를 다 삭제하고 있습니다...ㅎㅎ
과연 좋은 테스트인지 의심이 드네요🧐🧐..(🆘)

그럼 이번 미션 리뷰 잘 부탁드리겠습니다!!
코드에 대해 의문점이나 이상한 점이 있다면 언제든지 편하게 DM 주세요〰️
그럼 디우도 화이팅 하세요!!!🔥

2022-10-04 00:21 UTC, tco0427 requested changes
안녕하세요 페퍼!!
전체적으로 요구사항에 맞게 잘 구현해주셨네요!
몇가지 궁금한 점과 코멘트 남겼보았습니다😃

2022-10-04 00:21 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        Assert.notNull(sql, "SQL must not be null");
쿼리문에 대한 null 검사까지 꼼꼼하게 👍👍
제 미션에서도 적용해보아야겠네요ㅎㅎ

2022-10-04 00:21 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            results.add(rowMapper.mapRow(resultSet, rowNum++));
실제로 `mapRow()` 함수형 인터페이스를 구현하고 있는 로직에서 `rowNum` 을 사용하고 있는 부분이 없는 것 같아요!

2022-10-04 00:21 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +import org.springframework.util.Assert;
페퍼가 새롭게 만든 JDBC 라이브러리가 스프링 프레임워크에 종속적이기 보다는 스프링을 쓰지 않는 자바 환경에서도 활용할 수 있게 해보는 것은 어떨까요??ㅇㅅㅇ

2022-10-04 00:21 UTC, tco0427 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +                .willReturn("pepper");
오..!! 이렇게도 테스트해볼 수 있겠네요👍
제 테스트에서도 이렇게 개선해보아야겠네요ㅎㅎ
그런데 `queryForObject()` 가 2개 이상일 때 저희가 원하는 예외가 제대로 발생하는지 테스트를 추가해보는 것은 어떨까요??
혹은 관련 검증 부분을 별도로 분리해 그 쪽에서 단위테스트를 해볼 수도 있을 것 같아요!

2022-10-04 12:12 UTC, SuyeonChoi reviewed
안녕하세요 디우~!
바쁘실텐데 빠르고 꼼꼼한 리뷰 감사합니다🙇‍♀️🙇‍♀️
디우가 리뷰주신 내용들을 반영하였습니다! 

확인 부탁드릴게요. 리뷰 반영 외에 따로 건들인건 없습니다.
그럼 다시 한번 잘 부탁드리겠습니다〰️

2022-10-04 12:12 UTC, SuyeonChoi commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
> +        userDao.cleanUp();
디우 새로운 방향을 제시해주셔서 정말 감사합니다!!🙇‍♀️🙇‍♀️🙇‍♀️
프로덕션 코드에 테스트에만 사용하는 로직이 가장 크게 신경쓰였는데 스키마 파일을 이용하면 해결되는 문제였군요!!🤩
디우가 링크로 첨부해준 자료를 통해 TRUNCATE와 DELETE의 차이도 확실하게 알 수 있었어요. 
`schema.sql` 파일을 통해 데이터를 drop하는 방식으로 변경하였습니다.

반영한 커밋: 6c7d554d6fe76399235cfae4488eb32ff59c0efe

2022-10-04 23:41 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +    T mapRow(ResultSet resultSet, int rowNumber) throws SQLException;
오, 이러한 이유로 위와같은 인터페이스로 구현해주셨군요!!
좋은 자료 공유해주셔서 감사합니다!!👍

2022-10-04 23:52 UTC, tco0427 approved these changes
안녕하세요 페퍼! 
피드백 반영하고 코멘트 남겨주신 부분 확인하였습니다!
2단계에서 뵙겠습니다~_~

2022-10-04 23:52 UTC, tco0427 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +        void moreThanOneResult_ExceptionThrown() throws SQLException {
👍👍

2022-10-04 23:52 UTC, tco0427 commented on app/src/main/resources/schema.sql
> +drop table if exists user_history;
👍👍

2022-10-04 23:52 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            throw new DataAccessException("Incorrect result size: expected " + 1 + ", actual " + result.size());
사소한 부분이긴 한데..!
`"Incorrect result size: expected 1, actual " + result.size()` 이면 문자열 연산을 더 줄일 수 있을 것 같아서 코멘트 남겨봅니다~_~ (예외 메시지만 봐도 어떤 예외인지 한 눈에 파악 가능하겠네요👍👍)

2022-10-04 23:52 UTC, merged

2022-10-05 01:28 UTC, SuyeonChoi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            throw new DataAccessException("Incorrect result size: expected " + 1 + ", actual " + result.size());
다음 리뷰에서 반영하겠습니다!