[JDBC 라이브러리 구현하기 - 1단계] 썬(윤선용) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #112
Opened 2022-10-03 15:40 UTC by syoun602

안녕하세요 배카라~!
미션에서 뵙는건 처음이네요.
`JdbcTemplate`으로 분리해서 구현했더니, try-catch문이 중복되는게 거슬려서 `FunctionalInterface`를 이용해 분리해봤습니다~!

그럼 저를 따끔하게 혼내주세요.

2022-10-03 16:11 UTC, seong-wooo requested changes
# 안녕하세요 썬

리뷰 남겼습니다 ~ 최대한 빠르게 pr 날려주셨으면 좋겠어요! 저도 바빠요~~

2022-10-03 16:11 UTC, seong-wooo commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, preparedStatement -> {
가독성이 별로네요. 딱 보고 무슨 코드인지 파악이 안됐어요.
두번 째 인자를 변수로 빼는건 어떨까요?

2022-10-03 16:11 UTC, seong-wooo commented on jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +    T mapRow(ResultSet rs, int rowNum) throws SQLException;
rowNum은 어디에 쓰이나요??

2022-10-03 16:11 UTC, seong-wooo commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return update(preparedStatement);
`return preparedStatement.executeUpdate();` 이거 한 줄만 써도 괜찮지 않을까요?
굳이 메소드로 분리한 이유가 궁금합니다

2022-10-03 16:19 UTC, seong-wooo commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +                new TestUser(rs.getLong("id"), rs.getString("account")), 1L);
```java

final List<TestUser> users = jdbcTemplate.query(sql, (rs, rowNum) ->
                new TestUser(1L, "sun"), 1L)
```
이렇게 진행하면 불필요한 목킹을 줄일 수 있지 않을까요?

2022-10-04 05:23 UTC, syoun602 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return DataAccessUtils.singleResult(users);
`DataAccessUtils` 가 스프링 프레임워크에 포함된 객체인지 몰랐네요! `queryForObject` 메서드를 만들어서 의존을 제거해봤습니다

2022-10-04 05:40 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
> +    R doInStatement(T t) throws SQLException, DataAccessException;
오 좋네요! 커스텀 `FunctionalInterface`는 명시적으로 무슨 역할을 하고 있음을 알려주기 위해 작성했는데, 내부적으로 해당 역할을 하지 않았네요! 수정했습니다

2022-10-04 05:41 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, preparedStatement -> {
파라미터가 더 추가된다면, 가독성이 떨어질 수 있어 변수를 고민해보겠지만, 현재 구조에서는 쉽게 파악이 된다고 생각됩니다 😢

2022-10-04 05:43 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +    T mapRow(ResultSet rs, int rowNum) throws SQLException;
`rowNum`이 사실 데이터를 가져올때 몇개까지 가져올 것인지 확인하기 위함인데, 현재로써는 해당 기능을 사용하지 않을 것 같네요. 우선은 제거하고 추후에 필요할때 다시 구현하도록 하겠습니다!

2022-10-04 05:48 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return update(preparedStatement);
이부분은 바로 실행할 수도 있었으나, Exception을 분리하기 위해 따로 추가했습니다!

2022-10-04 05:57 UTC, syoun602 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +                new TestUser(rs.getLong("id"), rs.getString("account")), 1L);
`queryForObject`가 생겨나게 되어 해당 메서드를 테스트할 때 위와 같은 방식을 사용했고, 기존 `query()`메서드는 그대로 유지하였습니다~!

2022-10-04 06:05 UTC, seong-wooo requested changes
# 안녕하세요 썬

리뷰 하나 더 남겼습니다. ~

2022-10-04 06:05 UTC, seong-wooo commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        if (result.size() > 1) {
size가 0이면 어떻게 되는 건가요??

2022-10-05 00:58 UTC, merged

2022-10-05 00:58 UTC, seong-wooo commented
이만 머지할게요~ 다음 미션도 화이팅!