[JDBC 라이브러리 구현하기 - 2, 3단계] 차리(이찬주) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #131
Opened 2022-10-04 11:16 UTC by cjlee38

안녕하세요 마루 ~ 

아까 DM으로 말씀드렸다시피 2단계에서 뭘 해야할지 잘 모르겠어서, 우선 3단계까지 구현하고 PR 드립니다.

이전에 말씀드렸던 상속구조와 관련해서, 차라리 추상화 단계를 한 단계 더 높여 Update와 Query로 구분하는게 조금 더 어울릴 것 같다는 생각이 들어서 `ListExceution` 을 `QueryExecution`으로 바꾸고 `ObjectExecution`을 삭제하였습니다. 대신 `JdbcTemplate#QueryForObject` 에서는 `QueryExecution`을 활용하되, 반드시 단건의 요청만 처리할 수 있도록 수정하였습니다.

3단계를 진행하면서 뭔가 Transactional 어노테이션 기반으로 동작하게 만들어보고 싶어서 주어진 요구사항에 더해서 프록시 기반으로 동작할 수 있도록 가볍게 한번 만들어봤으니 이 점 참고 바랍니다. 날이 추운데 감기 조심하세요~

2022-10-06 01:48 UTC, kang-hyungu requested changes
차리, 피드백 참고하셔서 수정해보시기 바랍니다.
2단계 미션은 JdbcTemplate을 구현하는데 초점을 맞추기 보다 어떤 과정을 통해 중복을 제거하는지 리팩터링하는 경험을 해보시기 바랍니다.

그리고 테스트 코드가 너무 부족한데 다른 개발자도 검증할 수 있도록 테스트를 작성해보시기 바랍니다.

2022-10-06 01:48 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/dao/UserHistoryDao.java
> +                new Object[]{userHistory.getUserId(), userHistory.getAccount(), userHistory.getPassword(),
사용자 입장에서 매번 new Object를 만들어야 한다니 너무 번거롭겠네요.
가변인자를 사용해서 좀더 편리하게 만들 수 없을까요?

2022-10-06 01:48 UTC, kang-hyungu commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
> +        jdbcTemplate.update("drop table users if exists", null);
파라미터로 null을 전달해주는게 적절할까요?

2022-10-06 01:48 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/JdbcConnector.java
>  public class JdbcConnector {
이 클래스가 필요한가요?
JdbcTemplate 내부에서 메서드로 중복을 제거할 수 있는데 커넥터를 따로 클래스로 분리한 이유는 무엇인가요?

2022-10-06 01:48 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/execution/QueryExecution.java
> +public class QueryExecution<T> extends AbstractExecution<List<T>> {
AbstractExecution 클래스로 추상화가 필요한 상황인가요?
오히려 관리해야할 클래스가 늘어나진 않을까요?

그리고 리턴 타입을 List가 아닌 Set이나 Stream으로 확장하고 싶을 때는 지금 구조에서 유연하게 변경이 가능할까요?

2022-10-06 01:48 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/transaction/TransactionalProcessor.java
> +            if (!types[index].isAssignableFrom(arguments[index].getClass())) {
2뎁스 실화입니까 😫

2022-10-06 08:14 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/JdbcConnector.java
>  public class JdbcConnector {
주어진 SQL문과 더불어 여러 파라미터를 세팅하는 역할과, 실질적으로 커넥션을 연결하는 역할이 서로 다르다고 판단했습니다.

2022-10-06 08:17 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/execution/QueryExecution.java
> +public class QueryExecution<T> extends AbstractExecution<List<T>> {
AbstractExecution 자체에 대해서도 많이 고민하긴 했었는데, 우선 당장은 필요가 없는 것 같아 삭제했습니다. 다만 Execution 인터페이스는 람다를 활용하지 않는 쪽으로 선택하였습니다. 람다는 행동을 자유롭게 정의할 수 있는 반면, 이를 클래스로 정의하면 한정된 행동만 할 수 있다는 차이가 있다고 보았는데, 쿼리가 할 수 있는 행위를 분류해보았을 때 람다로 처리해야할 만큼 다양한 경우가 없을 것이라 생각하였습니다 !

2022-10-06 08:18 UTC, cjlee38 commented on app/src/main/java/com/techcourse/dao/UserHistoryDao.java
> +                new Object[]{userHistory.getUserId(), userHistory.getAccount(), userHistory.getPassword(),
가변인자로 수정하였습니다 :)

2022-10-06 08:18 UTC, cjlee38 commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
> +        jdbcTemplate.update("drop table users if exists", null);
가변인자로 수정하면서 삭제하였습니다 !

2022-10-06 08:19 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/transaction/TransactionalProcessor.java
> +            if (!types[index].isAssignableFrom(arguments[index].getClass())) {
깜빡하고 놓쳤네요. 스트림으로 처리할 수 있도록 수정하였습니다 ~

2022-10-08 15:58 UTC, chawani requested changes
차리 안녕하세요! 마루입니다
드디어 리뷰를 하게 되었네요😂 아직 2단계 머지가 안됐는데(ㅠㅠㅋㅋ) 리뷰를 위해 3단계를 미리 진행해보았어요😎
지난번에 고민하시던 부분에 대해서는 지금 코드가 좀 더 직관적이라고 느껴져서 개인적으로 좋네용
3단계까지 잘 구현해주셔서 크게 고칠 부분은 없어보이고 자잘한 부분과 궁금한 부분들에 코멘트를 남겼습니다!
끝까지 화이팅입니다💪

2022-10-08 15:58 UTC, chawani commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var userService = new ProgrammaticUserService(userDao, userHistoryDao);
ProgrammaticUserService 클래스는 무슨 역할을 하고 있나요?? TxWrappingUserService에 AppUserService를 주입해서 테스트를 통과 시킬 수 있을 것 같은데 ProgrammaticUserService를 어떤 의도로 만드신 건지 궁금해요!😯
실제로 바로 밑에 testTransactionRollbackWithWrapping 테스트 메서드를 통해서 제가 말씀드린 대로 테스트를 하고 계신데 두 테스트를 분리해야하는 이유가 무엇인가요??

2022-10-08 15:58 UTC, chawani commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return results.get(SINGLE_RESULT - 1);
개인적으로 이전보다 직관적이라고 느껴지네요👍
이미 알고계실 수도 있고 꼭 수정하기를 바라는 건 아닌데요, queryForObject에서 조회 결과가 0개일 때와 1개 초과일 때 발생하는 exception이 달라서 그걸 고려해보는 것도 좋을 것 같네용

2022-10-08 15:58 UTC, chawani commented on jdbc/src/main/java/nextstep/jdbc/execution/UpdateExecution.java
>      }
QueryExecution은 가변인자를 받도록 해놓으셔서 여기도 가변인자를 받는걸로 통일시키면 좋을 것 같네요!

2022-10-08 15:58 UTC, chawani commented on jdbc/src/main/java/nextstep/jdbc/transaction/TransactionalProcessor.java
> +                throw new RollbackException(e);
RollbackException이라고 네이밍하신 이유가 무엇인가요?🤔

2022-10-08 15:58 UTC, chawani commented on jdbc/src/test/java/nextstep/jdbc/execution/QueryExecutionTest.java
> +        );
```suggestion
                ), "hi"
        );
```
이제 이렇게 바꿔도 되겠네요!

2022-10-09 01:20 UTC, cjlee38 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var userService = new ProgrammaticUserService(userDao, userHistoryDao);
`ProgrammaticUserService`는 사용자가 직접 트랜잭션을 컨트롤하는 경우라고 가정하고 만들어본 케이스이고, `TxWrappingUserService` + `AppUserService`는 스프링에서 제공하는 프록시 기능을 수동으로 구현해서 사용하는 케이스, `DeclarativeUserService`는 `Transactional` 어노테이션을 이용해서 트랜잭션을 활용하는 케이스입니다 ~

2022-10-09 01:28 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/execution/UpdateExecution.java
>      }
그렇네용. 다른 부분도 가능한 가변ㅂ인자로 받도록 수정하였습니다.

2022-10-09 01:29 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/transaction/TransactionalProcessor.java
> +                throw new RollbackException(e);
원래 처음 만들때 생각에는 기존 트랜잭션 동작방식을 따라서 commit 하던 과정에서 문제가 발생하면 rollback exception을 던지는 흐름을 따라가려고했는데, 지금 다시 생각해보니까 여기서 발생한 에러는 커밋과정이 아니라 비즈니스 로직 진행하던 중에 문제가 발생한 케이스라.. rollback exception이 아닌 것 같아서 삭제했습니다 ㅋㅋ;

2022-10-09 01:29 UTC, cjlee38 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return results.get(SINGLE_RESULT - 1);
반영하였습니다 ~

2022-10-10 16:17 UTC, chawani approved these changes
차리 안녕하세요~ 리뷰 해드렸던 부분 다시 확인했고 이만 머지 해도 될 것 같네요! 고생 많으셨습니당😎👍

2022-10-10 16:17 UTC, merged