[JDBC 라이브러리 구현하기 - 1, 2단계] 코다(김윤정) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #14
Opened 2021-09-22 00:49 UTC by yjksw

춘식 안녕하세요 ~~!! 코다입니다 😊
못본지 너무 오래 되었는데 이렇게 리뷰어 리뷰이로 만날 수 있어서 정말 넘 반가워요 !!! 
얼른 다시 나갈 수 있었으면 하는 마음이 더 커지네요 ㅠㅠㅠㅠ

이번에 미션을 구현하면서 실제 JDBCTemplate 시그니처를 많이 참고하려고 했어요. 
그리고 더 분리가 필요한 부분에 대해서 나름 분리하여 깔끔하게 코드를 유지하려고 했습니다 ㅎㅎ

본래 setLong, setString 등으로 prepareStatement 인자를 지정하는데 라이브러리를 구현하면서 setObject로 통일하게 되더라구요 !! 
구체적으로 명시하는 것이랑 setObject로 하는 것의 장단점이 무엇일까 구현하면서 좀 고민했습니다.

테스트는 통과하지만 놓친 부분이 있는지 모르겠네요 !! 
잘 부탁드립니다 ~!! 🚀 🙌

2021-09-26 09:53 UTC, RinSabbit requested changes
안녕하세요 코다!! 넘 오랜만이네요!!!
빨리 제출해주셨는데 피드백이 늦어 죄송합니다 흑흑
코드를 깔끔하게 짜서 많이 배우고 갑니다!!
코멘트를 조금 남겨봤으니 확인 부탁드려요 😉

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    }
단일 행을 예상했는데 여러 행이 들어올 땐 오류가 나지 않는 건가요? 👀

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private <T> T execute(String sql, Object[] args, CallBack<T> sqlExecution) {
추상화 👍 👍 👍

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    protected DataSource datasource;
protected로 설정한 이유가 있을까요?

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void setArguments(PreparedStatement pstm, Object... args) throws SQLException {
private으로 바꿔도 될 거 같아요!

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>  public class JdbcTemplate {
사이트엔 명시되어 있지 않은데 강의에서 jdbcTemplate 테스트도 짜라고 했던 것 같아요...!! 👀
제 착각이라면 넘어가셔도 됩니다ㅎㅎ

2021-09-26 09:53 UTC, RinSabbit commented on README.md
> +    - [ ] application.properties에 DB 관련 정보 저장하여 app 모듈에 DataSource 코드 제거
이것도 나중에 추가될 예정인가요? :3

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/ResultSetExtractor.java
> +public class ResultSetExtractor {
👍 👍

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void setArguments(PreparedStatement pstm, Object... args) throws SQLException {
private로 바꿔도 될 것 같아요!!

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    protected DataSource datasource;
protected를 쓰는 이유가 있을까요?

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    }
단일 행을 예상했는데 여러 행이 들어올 땐 예외 처리를 안 하는 걸까요? 👀

2021-09-26 09:53 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>  public class JdbcTemplate {
사이트엔 명시되어 있지 않은데 강의에서 jdbctemplateTest를 짜라고 했던 걸로 기억해요...! 👀 
(제 착각일 수도 있으니 그냥 넘겨도 됩니다ㅎㅎ...)

2021-09-27 05:35 UTC, RinSabbit commented
오잉 지금 보니 코멘트 중복된 게 있어서 좀 지웠습니다ㅎㅎ

2021-09-27 05:37 UTC, kang-hyungu requested changes
코다 간단한 코멘트 남겼으니 참고하세요

2021-09-27 05:37 UTC, kang-hyungu commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
>  class UserDaoTest {
전체 테스트를 돌리니 실패하네요! 다시 점검해보아요

2021-09-27 05:50 UTC, yjksw commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    protected DataSource datasource;
엇... 기존에 JdbcTemplate을 추상클래스로 활용하다가 이후 리팩토링 했는데 그 때 protected로 지정한 것을 수정하지 않았네요 !! ㅠㅠㅠ 역시 매의 눈 춘식 👍 감사합니다 ~!!

2021-09-27 05:52 UTC, yjksw commented on README.md
> +    - [ ] application.properties에 DB 관련 정보 저장하여 app 모듈에 DataSource 코드 제거
yml 에서 datasource를 가져오려고 계획 중이었는데 생각보다 여유가 없어서 보류하려구요 ..ㅎㅎ 추후에 미션 끝난 이후에라도 해볼 생각입니다 !! 
또 transaction 관리 항목이 미션 홈페이지에 기재가 되어 있었는데 자동으로 해주는 transaction 관리 이외에 어떤것을 말하는지 잘 모르겠어서요!! 춘식은 어떤 transaction 관리가 필요하다고 생각하나요 ?

2021-09-27 09:40 UTC, yjksw commented on app/src/main/java/com/techcourse/dao/UserDao.java
>  public class UserDao {
춘식 말대로 기존 controller들을 모두 바꾸어 보았어요 ~~!!! 
본래 UserDao 가 하나만 생성이 되어서 자동주입 되는 것이 맞는 것 같은데 ㅠㅠ이번 미션 이외의 많은 구현이 필요한 것 같아서 
우선 매 controller에서 UserDao를 생성해서 사용하도록 수정했습니다 !!

2021-09-27 09:42 UTC, yjksw commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>  public class JdbcTemplate {
엇 그랬던것 같기도 하고 ..!!! 
이전에 구현하면서 라이브러리에 대한 테스트를 어떻게 해야할까 고민이 많았는데 아무리 해도 userDaoTest와 매우 중복되게 짜여지더라구요!! ㅠㅠ 
혹시 춘식은 어떤식으로 구현하는게 좋은 것 같은가요 ?!

2021-09-27 09:44 UTC, yjksw commented
안녕하세요 춘식 ~~!!!
좋은 피드백 감사합니다 ㅎㅎㅎㅎ
덕분에 놓친 부분들에 대해서 많이 보충할 수 있었어요 !!
춘식의 피드백에 따라서 
- 스키마에 drop table 제외 
- controller에 userdao 활용
- queryforObject에서 여러 결과가 나올 시 예외처리 
이렇게 크게 수정했습니다!!

더불어 춘식의 코멘트에 궁금한 점이나 대댓글도 남겼어요 !! ㅎㅎㅎ
감사합니다 ~~!!

2021-09-28 03:34 UTC, RinSabbit commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>  public class JdbcTemplate {
저는 jdbcTemplate이 제네릭하게 작동하는지 확인하고 싶어서 테스트할 때 내부 클래스로 Car 객체를 만들고 cars 라는 스키마를 따로 작성해서 테스트했어요!

2021-09-28 03:56 UTC, RinSabbit commented on README.md
> +    - [ ] application.properties에 DB 관련 정보 저장하여 app 모듈에 DataSource 코드 제거
굿굿 application.properties를 통해 datasource를 가져오는 거라면 피드백 강의에서 언급된 [HikariCP](https://github.com/brettwooldridge/HikariCP)를 참고하면 좋을 것 같아요!

트랜잭션 같은 경우는 Connection 객체가 기본적으로 setAutoCommit(true) 상태라, try-with-resoucre 를 통해 connection을 열고 닫는 게 일종의 트랜잭션 관리라고 받아들였어요!! 여러 sql을 한 메소드 내에서 날리거나 readOnly를 구현하고 싶으면 Connection의 commit과 rollback 등의 메소드를 이용해 구현하는 방법도 있지만, 저는 어려워서 패스했습니다ㅎㅎ

트랜잭션 구현 관련된 자료는 [여기](https://docs.oracle.com/javase/tutorial/jdbc/basics/transactions.html)를 참고하면 좋을 것 같아요 🙃

2021-09-28 04:16 UTC, RinSabbit commented
방가워요 코다~~!!! 피드백 반영한 거 확인했어요 ><
userDaoTest도 전체 테스트로 잘 돌아가네요 👍 
(우째선지 ServletTest가 하나 터지긴 하나 이 미션에서 중요한 부분은 아니니 넘어가도록 합시다 😆 )
댓글로 물어본 것도 코멘트 달아보았으니 확인 부탁드려효!!!!
Dao 자동주입에 대해선, ControllerScanner만 살짝(?) 갈아엎으면 충분히 할 수 있으니 나중에 시간 날 때 한번 도전해보세요 호호
혹시 이해가 안 되거나 더 궁금한 점은 디엠 주세용용

2021-09-28 04:31 UTC, merged

2021-09-28 08:43 UTC, yjksw commented on README.md
> +    - [ ] application.properties에 DB 관련 정보 저장하여 app 모듈에 DataSource 코드 제거
크으 춘식 짱!!!👍