[JDBC 라이브러리 구현하기 - 2단계] 알린(장원영) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #149
Opened 2022-10-06 09:24 UTC by OzRagwort

안녕하세요 소주캉 알린입니다. 

나름대로 리팩을 한다고 했봤는데 커밋의 수가 조금 적어보이네요 ㅠㅠ

저번에 따봉을 날려주신 [코드](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/101#discussion_r986714384)는 spring 프레임워크가 제공하는 기능이었습니다. 

덕분에 코드는 짧아지고 깔끔해졌는지 모르겠지만  이번 미션의 취지와 맞지않는 듯 하여 스프링 프레임워크와 연관된 녀석들(RowMapper포함)을 다 지우고 새로 구현해봤습니다. 

제 기준에서는 나름 열심히 리팩을 했는데 많이 부족할 것 같아요

조언 부탁드립니다!

2022-10-06 12:31 UTC, sojukang requested changes
안녕하세요 알린👋👋👋 JDBC 미션 2단계 리뷰 드리는 소주캉입니다. 

JdbcTemplate 관련 코드가 너무 깔끔해서 놀랐습니다👍
JdbcTemplateTest도 무척 꼼꼼하게 짜주셨더라구요😲
보면서 많이 배웠습니다. 

주로 알린의 생각을 묻는 리뷰를 달았습니다! 반영 해주셔도 좋고 안해주셔도 좋습니다. 감사합니다🙇‍♀️

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, statement -> executeQuery(statement, rowMapper), parameters);
깔끔하네요 👍

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            results.add(rowMapper.mapRow(rs));
mapRow가 반환하는 값을 찾아보지 않으면 한 번에 파악하기 힘들 수 있을 것 같아요. 로컬 변수로 분리하면 어떨까요?

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      private <T> T getSingleRow(final List<T> results) {
만약 result로 null이 들어온다면 NPE로 실패할 것 같아요!

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementFactory.java
> +public class PreparedStatementFactory {
생성 책임을 완전 분리하셨군요! static으로 활용하신다면 private 생성자로 인스턴스화를 막는 건 어떨까요?

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    private final RowMapper<User> userRowMapper = rs -> new User(
app에 있는 User를 JdbcTemplateTest에서 참조해도 되나? 라고 봤는데 inner Class로 선언한 것이었군요 👍. inner Class는 static으로 선언하면 어떨까요?
[Java의 내부 클래스는 static으로 선언하자](https://johngrib.github.io/wiki/java-inner-class-may-be-static/)
[Java inner class and static nested class](https://stackoverflow.com/questions/70324/java-inner-class-and-static-nested-class)

2022-10-06 12:31 UTC, sojukang commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>  class JdbcTemplateTest {
JdbcTemplateTest 꼼꼼하게 잘 작성해주셨네요👍👍👍. 
그런데 Framework의 일종으로 여러 Datasource에 관한 추상화된 접근을 제공하는 JdbcTemplate에서 H2로 한정된 테스트와 SQL 문법을 사용해도 될까요?

Jdbc 모듈에서는 Datasource 종류에 의존하지 않는 테스트를 작성하고, H2로 하는 테스트는 2차적으로 작성하거나 H2 vendor 측에서 작성해야하지 않을까요?

2022-10-07 06:37 UTC, OzRagwort commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private final RowMapper<User> userRowMapper = rs -> new User(
우선 RowMapper에 rowNum을 제거한 이유는 당장 필요하지않았고 앞으로도 제가 생각하는 선에서는 필요가 없다고 느꼈습니다. 

[스프링 프레임워크 이슈 글](https://github.com/spring-projects/spring-framework/issues/7796)에서 다른 개발자분들도 RowMapper는 인터페이스이기 때문에 어떤 식으로 구현될 지 모른다. 확장을 위해 추가해 두는게 좋아보인다는 느낌으로 되어있는 것 같습니다. 

JdbcTemplate에서 rowNum을 활용한다면 rs의 개수를 확인한다거나 특정 번째 row를 가져오고 싶을 때 사용할 수 있을 것 같습니다.
ResultSet에서는 데이터의 row를 포인터처럼 가르키고있고 rs.next(), rs.first(), rs.last() 등으로 이동할 수 있다고 알고있습니다.

```
rs.last();
int count = rs.getRow();
```
와 같이 사용하여 가져올 수도 있을 것 같고 

```
rs.absolute(rowNum);
```
으로 특정 번째 row로 이동하여 데이터를 받아올 수도 있을 것 같습니다.

2022-10-07 06:37 UTC, OzRagwort commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            results.add(rowMapper.mapRow(rs));
지금보니 그럴 것 같아요 수정하겠습니다!

2022-10-07 07:09 UTC, OzRagwort commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      private <T> T getSingleRow(final List<T> results) {
이 부분이 당장은 로직 흐름상 절대 null이 들어올 수 없다고 생각해서 null 체크를 하지 않았던 것 같아요!

꼼꼼하게 봐주셔서 감사합니당

2022-10-07 07:09 UTC, OzRagwort commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementFactory.java
> +public class PreparedStatementFactory {
감사합니다! 추가하겠습니다

2022-10-07 07:19 UTC, OzRagwort commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    private final RowMapper<User> userRowMapper = rs -> new User(
어쩐지 인텔리제이에서도 추천을 해주던데 이러한 이유가 있었군요

메모리 누수 방지 잘 기억하겠습니다! 

감사합니다

2022-10-07 09:09 UTC, OzRagwort commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>  class JdbcTemplateTest {
제가 생각하지 못한 부분을 말해주셔서 감사합니다

그런데 어떻게 해야 Datasource 종류에 의존하지 않는 테스트를 짤 수 있지?를 고민 고민 하다가 소주캉의 PR을 보고 배우면서 수정해봤습니다 

평소에 mocking을 잘 하지않았고 조금 부정적으로 생각하고있었었는데 이런 경우에는 mock이 큰 도움이 될 수 있을 것 같아요!

감사합니다 소주캉!

2022-10-09 15:27 UTC, sojukang commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    private final RowMapper<User> userRowMapper = rs -> new User(
크 엄청 자세하게 조사하셨군요 👍👍👍 저도 배워갑니다.

2022-10-09 15:27 UTC, sojukang commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, statement -> executeQuery(statement, rowMapper), parameters);
왜 역 따봉을 달아주셨죠? ㅠㅠ

2022-10-09 15:27 UTC, sojukang commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    private final RowMapper<User> userRowMapper = rs -> new User(
인텔리제이가 생각보다 똑똑하더라고유 ㅋㅋㅋ

2022-10-09 15:28 UTC, sojukang commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>  class JdbcTemplateTest {
저도 Mocking을 완전 좋아하지는 않는데 꼭 필요한 경우가 있기는 하더라고요... 그래서 이번에 빡세게 도입을 한번 해봤습니다🧐

2022-10-09 15:30 UTC, sojukang commented
안녕하세요 알린👋👋👋 JDBC 2단계 미션 리뷰드리는 소주캉입니다.
피드백 반영 잘 해주시고 댓글도 잘 남겨주셔서 너무 좋았어요👍👍
저도 2단계 알린 코드 보면서 깔끔하고 테스트도 잘 짜주셔서 보고 많이 배웠습니다🧑‍💻
3단계도 잘 부탁드립니다🙇‍♀️

2022-10-09 15:31 UTC, sojukang approved these changes
안녕하세요 알린👋👋👋 JDBC 2단계 미션 리뷰드리는 소주캉입니다.
피드백 반영 잘 해주시고 댓글도 잘 남겨주셔서 너무 좋았어요👍👍
저도 2단계 알린 코드 보면서 깔끔하고 테스트도 잘 짜주셔서 보고 많이 배웠습니다🧑‍💻
3단계도 잘 부탁드립니다🙇‍♀️

2022-10-09 15:31 UTC, merged