[JDBC 라이브러리 구현하기 - 2단계] 잉(유영우) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #158
Opened 2022-10-07 02:19 UTC by Yboyu0u

안녕하세요 호호✋🏻 2단계로 다시 찾아 뵙게 돼서 영광입니다. 
날씨가 쌀쌀해졌는데 감기 조심하세요🙏🏻

2022-10-08 12:20 UTC, yhh1056 requested changes
안녕하세요 잉~ 2단계에서 다시 뵙네요
저는 이미 감기가 걸려버렸습니다😭 잉도 감기조심하세요~

2단계 미션도 잘 구현해주셨네요!!👍
이번 요구사항에 맞게 분리할 수 있는 부분에 대해 리뷰남겼습니다~

Executable을 사용해서 catch에 대한 중복제거가 굿굿이네요!

제가 저번 리뷰때 남기지 못 한 부분이 있었는데 `queryForObject`의 반환로직을 보면
result.get(0)으로 결과를 가져오고있어요. 결과가 없거나 2개 이상이 반환되는 경우에 대한 체크가 필요해보이네요!! 검증로직을 추가하고 그 책임도 분리해보면 좋을 것 같아요.
`DataAccessUtils` 클래스의 메서드를 참고해보셔요~!

jdbcTemplate에 대한 테스트 작성도 하면 좋을 듯 한데요! 3단계 미션도 남고 시간이 많지 않으니 위 리뷰에 대한부분만 고민해보고 반영해주시면 머지할게요!! 테스트는 차차 작성해주시면👍👍👍

2022-10-08 12:20 UTC, yhh1056 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>          }
해당 책임을 분리해볼까요? 

PreparedStatementSetter 인터페이스를 참고해보면 도움이 될거에요!

그 다음엔 가변인자를 받아서 어떻게 처리할지 고민해보고 리팩토링하면 됩니다!!

2022-10-08 12:25 UTC, yhh1056 commented
++ preparedStatement.executeUpdate() 반환값은 어떤건지 알아보면 좋을 것 같아요!!

2022-10-10 11:21 UTC, Yboyu0u commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>          }
알려주신대로 `PreparedStatementSetter 인터페이스` 참고 하여 분리해 봤습니다!! 좋은 정보 감사합니다🙏🏻

2022-10-10 16:47 UTC, Yboyu0u commented
안녕하세요 호호✋🏻 
주신 리뷰 덕분에 JDBC의 내부 구조에 대해 좀 더 명확하게 알게 되었습니다. 감사합니다.
오늘 보니까 내일이 마지막 pr날이더라고요... 그래서 부득이하게 3단계를 이 pr에 추가로 해보았습니다🥲 
날씨가 점점 추워지네요. 따뜻하게 입고 다니세요(감기도 빨리 나으시길 바라겠습니다.)🙏🏻🥶🧥 
고생이 많으십니다.

2022-10-11 10:36 UTC, yhh1056 requested changes
트랜잭션 미션도 잘 구현해주셨네요!!

테스트 코드도 작성👍👍👍
수정할 부분이 있어서 리뷰남겼습니다! 금방 반영하실거에요~!

2022-10-11 10:36 UTC, yhh1056 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    private void execute(Runnable runnable) {
분리 좋네요!

2022-10-11 10:36 UTC, yhh1056 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        execute(() ->  userService.insert(user));
띄어쓰기 들어갔네요!

2022-10-11 10:36 UTC, yhh1056 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +           runnable.run();
여기도 띄어쓰기가 필요하네요!

2022-10-14 06:42 UTC, yhh1056 commented
마지막 미션까지 수고많으셨어요~!!! 머지하도록 하겠습니다~!

2022-10-14 06:42 UTC, merged