[JDBC 라이브러리 구현하기 - 2, 3단계] 범고래(조충범) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #198
Opened 2022-10-10 10:27 UTC by cndqjacndqja

안녕하세요 썬!
2단계만 구현하고 PR 날리려다 너무 조금 변경된 것 같아서 3단계랑 함께 보내게 되었습니다..! 🙇‍♂️
잘부탁드립니다! :)

2022-10-13 02:08 UTC, syoun602 requested changes
안녕하세요 범고래! 3단계 너무 잘 적용해주셔서 크게 변경할 부분은 없네요!!
간단한 리뷰 남겨놨으니 고민해보시고 적용해주세요!! 그럼 남은 기간도 화이팅

2022-10-13 02:08 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return result;
`DataSourceUtils.releaseConnection()`에 대해 알아볼까요?

2022-10-13 02:08 UTC, syoun602 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    private final PlatformTransactionManager transactionManager;
로컬 트랜잭션과 글로벌 트랜잭션의 차이가 어떻게 될까요?!
그냥 범고래의 의견만 들려주세요!!

2022-10-14 04:38 UTC, cndqjacndqja commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return result;
PlatformTransactionManager는 Connection을 ThreadLocal로 관리하고 있는데요!
transactionManager를 commit했을 때, 커밋 후 releaseConnection()를 호출해 주는 것으로 이해했습니다.

`DataSourceUtils.releaseConnection()`는 외부에서 관리되지 않는 경우(ThreadLocal에서 사용하는 것 외에 다른 스레드가 사용하고 있지 않은 경우) Connection을 닫는 것으로 알고 있습니다 :)

2022-10-14 04:55 UTC, cndqjacndqja commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    private final PlatformTransactionManager transactionManager;
로컬 트랜잭션은 리소스 매니저의 드라이버를 사용해서 로컬 트랜잭션을 시작하거나 종료하고, 글로벌 트랜잭션은 2개 이상의 리소스 매니저를 사용해도 이 트랜잭션들을 하나의 글로벌 트랜잭션으로 묶어서 처리할 수 있다는 차이가 있는 것으로 이해했습니다 :)
그래서 저희는 스프링에서 PlatformTransactionManager를 사용했을 때, 다른 데이터 접근 기술을 사용하더라도 하나의 트랜잭션으로 묶어서 처리할 수 있구나 생각했어요!

혹시 제가 이해한 것이 맞을까요??

2022-10-14 04:59 UTC, cndqjacndqja commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
썬은 현재 코드에서 insert에 트랜잭션을 적용하여 얻는 이점이 어떤 것이라고 생각할까요 ? 😄

2022-10-15 07:17 UTC, syoun602 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
사실 저도 하나의 sql을 실행시키는데 transaction이 필요하다고 생각되지는 않아요!
하지만 저는 명시적으로 붙여놓긴 했습니다! 사실 `userService` 내부의 로직은 `dao.insert()`를
호출하는 것 밖에는 없지만, 현재와 같이 프록시 패턴인 경우, 내부적으로 클래스를 매번 들어가서 
trasaction이 필요한지 확인해보는 것보다는 맘 편히 미리 붙여놓는게 좋아보였습니다!
또한, 추후에 bulk insert나 추가적인 작업이 늘어날 경우 그때되서 붙이는 것보다는 미리 해놓는게 좋아보여서 물어봤습니다 :)

2022-10-15 07:20 UTC, syoun602 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return result;
그렇다면 현재 범고래의 `JDBCTemplate`을 사용한다면 Service 내부에서 TransactionManager를 사용하지 않을 때 connection이 안닫힐 것 같네요 😢

2022-10-15 07:22 UTC, syoun602 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    private final PlatformTransactionManager transactionManager;
넵 저도 똑같이 이해했습니다 😊

2022-10-15 07:30 UTC, syoun602 approved these changes

2022-10-15 07:30 UTC, syoun602 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
코드가 중복되네요! 추후에 FunctionalInterface를 사용해서 중복 제거도 해볼 수 있을 것 같아요 :)

2022-10-15 07:31 UTC, merged