[JDBC 라이브러리 구현하기 - 2, 3단계] 후디(조동현) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #199
Opened 2022-10-10 11:10 UTC by devHudi

안녕하세요, 리차드 🎶 뭔가 오랜만에 리뷰 요청 드리는 것 같네요 😅
2단계 힌트를 보니 이미 1단계에서 미션 의도대로 설계가 된 것 같아서 지난번 말씀드린 것 처럼 3단계까지 함께 리뷰 요청 드려요.
(혹시 2단계 리팩토링 부분에서 제가 놓친게 있다면 리뷰 부탁드립니다 ㅎㅎ;)

3단계는 스프링이 트랜잭션 동기화와 추상화를 어떻게 하고 있는지 이해가 필요해서 조금 오래걸렸던 것 같아요.
관련하여 공부를 좀 했는데 https://hudi.blog/spring-transaction-synchronization-and-abstraction/ 에 정리해두었으니 참고하면 좋을 것 같아요.

이번 리뷰도 잘 부탁드립니다 👋

2022-10-11 05:24 UTC, HJ-Rich requested changes
후디~ 빠르게 잘 구현해주셨네요! 💯
훌륭합니다~! 👏👏👏

몇가지 소소한 의견 남겨봤습니다.
필수 요구사항은 이미 모두 충족하셔서 선택적으로 반영해주시면 될 것 같습니다.

그리고 혹시 가능하시다면 JdbcTemplateTest를 구현해보시는 것도 도움이 될 것 같습니다.
거의 다 왔네요~! 화이팅! 🎶

2022-10-11 05:24 UTC, HJ-Rich commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
테스트에서만 사용되는 메서드를 프로덕션에 구현하는 방법에 대해 후디는 어떤 의견이신가요?~
그리고 현재 방식이라면 JDBC 벤더사가 달라지면 truncate 문법이 달라질 수 있어서 이슈가 될 수 있을 것 같아요~!

2022-10-11 05:24 UTC, HJ-Rich commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
JdbcTemplate은 DataAccessException 만 던지는데요,
RuntimeException으로 잡아주신 후디의 생각이 궁금합니다!

2022-10-11 05:24 UTC, HJ-Rich commented on app/src/test/java/com/techcourse/service/AppUserServiceTest.java
>          assertThat(actual.getPassword()).isNotEqualTo(newPassword);
sysout 발견~! 😆

2022-10-11 05:24 UTC, HJ-Rich commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>          }
👍

2022-10-11 05:24 UTC, HJ-Rich commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
64번 라인에 TODO 는 혹시 작업이 완료된 걸까요?!

2022-10-11 05:24 UTC, HJ-Rich commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> -             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
해당 라인에 남길 수 없어서 여기에 남깁니다 ! ㅎ
50번 라인을 이렇게 해보면 어떨까요?
JdbcTemplate의 실제 구현이 이렇게 되어있더라고요~

AS-IS
`return results.get(FIRST_RESULT_INDEX);`

TO-BE
`return results.iterator().next();`

2022-10-13 03:35 UTC, devHudi commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
`TransactionManager` 가 `TransactionException` 을 함께 던지기 때문에 `RuntimeException` 으로 묶어 처리했습니다!

2022-10-13 03:36 UTC, devHudi commented on app/src/test/java/com/techcourse/service/AppUserServiceTest.java
>          assertThat(actual.getPassword()).isNotEqualTo(newPassword);
오 매의눈~! 제거했습니다!

2022-10-13 03:41 UTC, devHudi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
이대로 예외 던지기로 해서 TODO 코멘트를 지웠습니다!

2022-10-13 03:55 UTC, devHudi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> -             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
오 너무 좋은 아이디어네요! 앞으로도 첫번째 값만 필요하면 이터레이터를 가져와서 사용하는 방법을 써야겠네요 👍

2022-10-13 04:06 UTC, merged

2022-10-13 04:06 UTC, HJ-Rich commented
후디 고생 많으셨습니다! 👍