[JDBC 라이브러리 구현하기 - 1, 2단계] 마크(김병화) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #20
Opened 2021-09-23 00:53 UTC by binghe819

### 하이 샐리~~

이전에 토비의 스프링을 읽어서 JDBCTemplate 구현 관련해선 큰 어려움은 없었어요!

그래서 이렇게 내도 되나 싶긴 하네요..ㅋㅋㅋㅋㅋ

조금 욕심을 부려보자면 아래 사항들을 구현하면 좋을 듯한데.. 일단은 보류할게요 :) (이 수업만 듣는건 아니잖아요^^)
- `queryForObject`할때 `Object`를 리플렉션으로 상태 값에 따라 인스턴스 만들어 반환해주는 기능 (Converter 비슷한 기능)
- JDBC 트랜잭션 설정

> 테스트 코드를 작성하지 않아서 코드가 만족스럽진 않지만 일단은 요구사항에 맞춰 구현하여 냅니다! 편하게 피드백 주세요~~

2021-09-23 15:15 UTC, dusdn1702 requested changes
안녕하세요 마크 ㅋ ㅋ ㅋ 👨🏻‍💻
리뷰를 열렬히 하고 싶었는데 생각보다 깔끔하고 멋진 구현에 또 많이 배우고 갑니다~~
abstract에서 커넥션을 관리하고, 구현체에서 필요한 구현을 다루는 것이 특히나 인상적이었어요!!👍
코드에 대해서는 양도 길지 않아 별다르게 피드백 드릴 부분이 없었네용 ^0^

그치만!! UserDao를 이렇게 멋지게 구현했으니 app에서 InmemoryRepository 대신 UserDao를 사용해보고 잘 동작하는지 보는 것 어떨까요~~?? >-<

2021-09-23 15:15 UTC, dusdn1702 commented on app/src/main/java/com/techcourse/dao/UserDao.java
오 옵셔널 사용 굿~~!👏

2021-09-23 15:15 UTC, dusdn1702 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        }
finally에 코드가 없는데 제거해도 되지 않을까요~~?

2021-09-23 15:15 UTC, dusdn1702 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        });
람다 굿~~👍

2021-09-23 15:15 UTC, dusdn1702 commented on jdbc/src/main/java/nextstep/jdbc/exception/DataAccessException.java
> +}
오 커스텀 익셉션까지~~~

2021-09-23 23:32 UTC, sihyung92 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        try (Connection conn = dataSource.getConnection();
tryWithResources문이 반복되요. 
DRY(Don't Repeat Yourself) 원칙에 따라 중복을 제거해보는 것은 어떨지요?

2021-09-23 23:33 UTC, sihyung92 commented
리뷰어 코멘트가 상큼해서 저도 모르게 들어왔습니다 온 김에 훈수두고 갑니다 감사합니다

2021-09-24 06:54 UTC, bperhaps commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        try (Connection conn = dataSource.getConnection();
싫은데요? 깔깔

2021-09-25 07:39 UTC, binghe819 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        try (Connection conn = dataSource.getConnection();
싫은데요? 깔깔

2021-09-25 07:58 UTC, binghe819 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        try (Connection conn = dataSource.getConnection();
ㅋㅋㅋㅋ 분리했습니당~

2021-09-25 08:24 UTC, sihyung92 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        doBinghe(stmt, new Binghe<Integer>() {
굳이 내부 익명 인터페이스 형식으로 작성한 이유가 있나요? :))

2021-09-25 08:27 UTC, sihyung92 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +public abstract class AbstractJdbcTemplate {
abstract 키워드를 활용한 부분이 없는데, 왜 익명클래스로 구현했을까요?

2021-09-25 15:58 UTC, dusdn1702 approved these changes
안녕하세요 마크~~~~😝
말씀드린 부분들을 잘 적용해주셨네요~~~~👍

근데!!!! 제가 직접 돌려보니까 db 관련 부분이 나오면 500 에러가 발생하더라구요~?~?~?
이부분만 수정하시면 될 것 같아서 이번 미션은 여기서 마무리하도록 하겠습니다 ㅎㅎㅎ

바쁜 와중에 미션까지 진행하시느라 수고 많으셨어요~~!!
얼마 남지 않은 시간 마저 같이 힘내보아요~~~💪

2021-09-25 15:58 UTC, dusdn1702 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +//        doBinghe(stmt, PreparedStatement::executeUpdate);
삭제가 안된것 같아요!!! 👀

2021-09-25 15:58 UTC, dusdn1702 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +    private <T> T doBinghe(StatementStrategy stmt, Binghe<T> binghe) {
doBinghe랑 Binghe는 도대체 뭐죠.....? 의도하신 바가 맞을까요.....?👀

2021-09-27 05:48 UTC, binghe819 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +    private <T> T doBinghe(StatementStrategy stmt, Binghe<T> binghe) {
앗... 네이밍 바꾼다고 한걸 까먹었네요ㅠ 수정할게요 :)

2021-09-27 06:26 UTC, kang-hyungu requested changes
마크 간단한 피드백 남겼으니 참고하세요

2021-09-27 06:26 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return this.jdbcTemplate.query(sql, mapper, id)
list를 반환해서 findFirst하는 것보다 객체 하나를 반환하는 메서드를 쓰는게 낫지 않나요?

2021-09-27 06:26 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +    private interface executor<T> {
자바 컨벤션을 지켜주세요

2021-09-27 06:26 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +        return execute(stmt, new executor<T>() {
람다를 사용하면 코드가 더 간결해지겠네요

2021-09-27 06:26 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +public class AbstractJdbcTemplate {
1. class 대신 추상 클래스로 만들면 어떨까요?
2. 추상 클래스가 필요한 상황인가요?

2021-09-28 13:51 UTC, binghe819 commented on jdbc/src/main/java/nextstep/jdbc/AbstractJdbcTemplate.java
> +public class AbstractJdbcTemplate {
흠.. 지금 생각해보니 굳이 추상 클래스를 사용할 이유는 없어보이네요ㅎㅎ

피드백 감사합니다 :)

2021-09-28 14:14 UTC, merged