[JDBC 라이브러리 구현하기 - 2, 3단계] 쿼리치(정석윤) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #212
Opened 2022-10-11 01:28 UTC by meatsby

안녕하세요 기론! 저번에 말씀드린대로 2, 3단계 함께 구현하여 제출합니다!
이번 미션도 잘 부탁드리겠습니다 🙇🏻‍♂️

2022-10-13 03:17 UTC, Gyuchool requested changes
안녕하세요 쿼리치~ 깔끔하게 진행해주셨네요
소소한 리뷰 남겼습니다~!

2022-10-13 03:17 UTC, Gyuchool commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        return userService.findById(id);
`findById()`와 `insert()`에는 트랜잭션을 걸지않은 이유가 있을까요?

2022-10-13 03:17 UTC, Gyuchool commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public void changePassword(final long id, final String newPassword, final String createBy) {
커넥션을 close하지 않아주는거 같네욥 
close해야할 것 같습니다

2022-10-14 03:08 UTC, meatsby commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        return userService.findById(id);
`insert` 메서드는 추가해줘야겠네요.. ㅎㅎ `findById` 는 원자성을 보장하고 조회용이기 때문에 트랜잭션이 불필요해보여서 걸지 않았습니다!

2022-10-14 09:13 UTC, Gyuchool approved these changes
쿼리치 수고하셨습니다~!
미션은 이만 머지할게욥

2022-10-14 09:13 UTC, merged