[JDBC 라이브러리 구현하기 - 2,3단계] 알렉스(이영환) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #217
Opened 2022-10-11 03:52 UTC by yxxnghwan

안녕하세요 야호!
제출이 많이 늦어졌네요..ㅠㅠ
사실 오늘이 막 PR 마감인줄 몰랐습니다..

급하게 숙제식으로 미션을 하느라 신경을 많이 못썼는데요,
남은 시간동안 추가적인 학습 해보면서 미션에 아는 만큼 반영해보겠습니다!

그럼 이번에도 잘 부탁드려요!

2022-10-11 06:40 UTC, pup-paw requested changes
안녕하세요 알렉스! 야호입니다 :)
궁금한 부분에 대해서 리뷰 남겨두었으니 확인 부탁드려요~
추가로 이야기 나눠보고 싶은 내용이나 궁금한 내용이 있으면 dm 주세요~!~!

2022-10-13 03:03 UTC, yxxnghwan commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            userService.insert(user);
깜빡한게 맞네요 ㅠㅠ 야호 리뷰대로 insert를 테스트에서 사용해보다 보니 작성한 코드에 버그가 있었던 것도 발견했어요..ㅠㅠ
코드 변경했습니다!

2022-10-13 03:05 UTC, yxxnghwan commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            transactionManager.commit(transaction);
스프링의 트랜잭션에서 영감을 받았는데 스프링에선 RuntimeException이 발생하면 트랜잭션을 롤백하고 Checked Exception이 발생하면 현재 작업까지 그냥 커밋해버리게 되어있어서 그렇게 구현했습니다!

2022-10-13 03:08 UTC, yxxnghwan commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
TxService 클래스는 모든 서비스의 메서드를 트랜잭션으로 포장하게 했어요!
작업이 딱 한 줄인데 트랜잭션으로 묶을 필요가 있나? 라는 고민을 해볼 수 있지만,
TxService 입장에선 Service의 내부 로직을 모르기 때문이에요.
그리고 JPA같은 경우는 트랜잭션 안에서만 작업이 가능하기도 하구요!
최대한 구현 기술에도 의존하지 않길 바래서 저렇게 작성했던 것 같네요!

2022-10-17 03:52 UTC, pup-paw approved these changes
안녕하세요 알렉스!! 야호입니다 :)
코멘트 반영과 답변 모두 확인 했습니다~~ 마지막 미션 수고하셨어요!!

2022-10-17 03:52 UTC, merged