[JDBC 라이브러리 구현하기 - 3단계] 페퍼(최수연) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #220
Opened 2022-10-11 04:36 UTC by SuyeonChoi

안녕하세요 디우!
아쉽게도 이번 미션의 마지막 PR이네요,,
디우가 2단계를 빠르게 확인해주셔서 저도 여유있게 작업할 수 있었습니다!
감사해용🙇‍♀️

---
이번 미션에 있던 질문도 함께 공유하고 싶어서 PR에 첨부해봅니다,,
> 왜 스프링은 PlatformTransactionManager로 트랜잭션을 관리할까?
PlatformTransactionManager 인터페이스는 트랜잭션 동기화 외에 다른 이유로도 사용된다.
로컬 트랜잭션, 글로벌 트랜잭션, JTA 라는 세 가지 키워드와 같이 학습해보자.

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/28749734/194997487-baf3d07e-9374-4c64-a286-84755d602b25.png">

를 생각해보았는데요. 트랜잭션을 사용하기 위해 경계를 설정하다 보니 
1. 서비스 코드가 복잡해진다.
2. 코드가 데이터 액세스 기술에 의존적이다.
3. 비즈니스 로직과는 다른 관심사(트랜잭션 경계설정)의 일을 수행한다.

는 단점이 생겼고, `PlatformTransactionManager`을 사용해서 1번 단점을 개선할 수 있었습니다.
DataSourceTransactionManager, JpaTransactionManager 두 매니저는 하나의 데이터베이스를 사용하거나 각각의 데이터를 독립적으로 사용하는 로컬 트랜잭션의 경우에 사용할 수 있습니다. 만약 하나 이상의 데이터베이스가 참여하는 경우는, 글로벌 트랜잭션에 사용되는 JtaTransactionManager를 사용할 수 있습니다. 이를 통해 여러개의 데이터베이스에 대한 작업을 하나의 트랜잭션으로 묶을 수 있고, 다른 서버에 분산된 것도 묶을 수 있다고 합니다. 
동기화 외의 기능은 조금 더 공부해야할거 같아요 

`@Transactional` 애너테이션을 생성해서 선언적 트랜잭션까지 구현해 비즈니스로직 외의 코드가 서비스에 없도록 만들고 싶었는데요,,
이부분은 시간 상 구현하지 못한게 아쉽습니다😭😭

그럼 이번 리뷰도 잘부탁드릴게요!🙇‍♀️🙇‍♀️

2022-10-11 23:41 UTC, tco0427 requested changes
안녕하세요 페퍼!!
이번 3단계도 너무 잘 진행해주셔서 크게 코멘트 남길게 없네요ㅎ.ㅎ
미션에 있던 질문에 대한 생각도 공유해주셔서 감사합니다!!

2022-10-11 23:41 UTC, tco0427 commented on README.md
> +- [x] 트랜잭션 서비스 추상화 - 트랜잭션 서비스를 추상화하여 비즈니스 로직과 데이터 액세스 로직을 분리
정리를 정말 깔끔하게 잘 해주셨네요!! 👍👍
기능 요구사항을 통해 학습해야 하는 내용을 확실히 학습하셨다는게 느껴졌습니다!!

2022-10-11 23:41 UTC, tco0427 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
findById 같은 곳에서 `NoSuchElementException` 이용해서 예외가 발생한 경우에 대한 메시지를 잘 만들어주셨더라구요!!👍
혹시 롤백되는 경우에 대해서도 예외 메시지나 혹은 로그를 통해서 메시지를 함께 보여줘보는건 어떨까요??😃

2022-10-11 23:41 UTC, tco0427 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public TxUserService(final PlatformTransactionManager transactionManager, final UserService userService) {
저의 경우, 미션 예시 코드에서 PlatformTransactionManager를 받도록 되어 있어서 저도 처음에는 이렇게 생성자를 정의해주었었는데, '트랜잭션 유저 서비스' 이니 트랜잭션 관리는 TxUserService 가 알아서 하게끔 하고, 어떤 비즈니스 서비스를 처리할지만 알려주면 되지 않을까? 생각하여 다음과 같이 구현해주었습니다.

```java
    public TxUserService(UserService userService) {
        this.transactionManager = new DataSourceTransactionManager(DataSourceConfig.getInstance());
        this.userService = userService;
    }
```

그런데 페퍼가 PR에 정리해주신 내용을 보고 나니, 여러 트랜잭션 매니저 중에서 선택해서 넘길 수 있도록 PlatformtransactionManager와 UserService 를 생성시에 모두 받도록 구현하는게 나을 것 같다는 생각도 들었어요..!!
여기에 대한 페퍼의 의견을 들어보고 싶어서 코멘트 남겨봅니다!!😃

2022-10-11 23:41 UTC, tco0427 commented on app/src/test/java/com/techcourse/service/AppUserServiceTest.java
> +    void testChangePassword() {
`비밀번호 변경` 이라는 비즈니스 로직에 대한 동작을 확인하는 테스트를 AppUserService로 분리해주셨군요!! 생각못해봤었는데..제 미션에도 적용해봐야겠네요!👍👍

2022-10-11 23:41 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        validateSingleResult(result);
이전 코멘트 반영해주셨네요!😃

2022-10-11 23:41 UTC, tco0427 commented on jdbc/src/test/java/nextstep/jdbc/RowMapperResultSetExtractorTest.java
> +    void extractData() throws SQLException {
꼼꼼한 테스트 작성!!👍👍

2022-10-11 23:41 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, preparedStatementSetter, preparedStatement -> {
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/66#discussion_r985212234

ResultSet의 경우 직접적인 close(AuthClosable한 자원이므로 try-with-resources 활용)을 해주지 않아도 해당 ResultSet을 생성한 Statement가 닫히거나 또는 executeQuery 메소드를 실행하는 경우 close() 된다고 하더라구요..!!
[JDBC API](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html)

그래서 혹시 다음과 같이 변경함으로써 try 구문을 제거해보는것이 어떤지 제안드려봅니다..!!

```java
        return execute(sql, preparedStatementSetter, preparedStatement -> {
            final ResultSet resultSet = preparedStatement.executeQuery();
            return resultSetExtractor.extractData(resultSet);
        });
```

2022-10-14 02:55 UTC, SuyeonChoi reviewed
안녕하세요 디우!
리뷰 반영이 늦어져서 죄송합니다😭😭
디우의 학습 공유 뿐만 아니라 따듯한 칭찬도 함께 리뷰 주셔서 피드백을 반영하는 동안 즐거웠습니다🥳 
코드 리뷰를 통해 이야기를 나눌 수 있던 것도 재미있었어요👏👏

디우가 언급한 피드백은 모두 반영했습니다👍
그럼 이번 리뷰 요청도 잘 부탁드리겠습니다〰️🙇‍♀️🙇‍♀️

2022-10-14 02:55 UTC, SuyeonChoi commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        }
예외 메세지를 통해 어떤 상황이 발생했는지 명확하게 나타내주었습니다👍

2022-10-14 02:55 UTC, SuyeonChoi commented on jdbc/src/test/java/nextstep/jdbc/RowMapperResultSetExtractorTest.java
> +    void extractData() throws SQLException {
감사합니다 디우!🙇‍♀️🙇‍♀️

2022-10-14 02:55 UTC, SuyeonChoi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, preparedStatementSetter, preparedStatement -> {
오 이렇게 새로운 사실을 하나 알아가네요! 디우 꼼꼼하게 학습한 부분까지 공유해주셔서 감사합니다👍👍
try 구문을 제거하고 불필요하게 늘어난 인덴트 길이를 개선할 수 있었어요👏

2022-10-14 02:55 UTC, SuyeonChoi commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public TxUserService(final PlatformTransactionManager transactionManager, final UserService userService) {
넵! 디우가 말했듯이 저는 여러 개의 `PlatformtransactionManager` 구현체 중, 상황마다 필요한 객체를 `TxUserService`로 전달해주는 방식을 선택했습니다. `TxUserService`가 트랜잭션을 관리해주는 클래스는 맞지만, 만약 클래스 내부에서 구현체를 정의해준다면 매우 높은 결합도를 갖게 된다고 생각합니다. 그리고 높은 결합도는 
- 클래스를 수정하려는 경우 연관된 클래스도 함께 이해해야한다
- 구현체 클래스가 변경되면 이를 반영해야한다(파급 효과)
- 재사용이 힘들다

는 단점이 있습니다. 그래서 생성자에서 구현체를 주입받는 방식을 선택하였습니다!🤓🤓

2022-10-14 11:00 UTC, tco0427 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    public TxUserService(final PlatformTransactionManager transactionManager, final UserService userService) {
`클래스를 수정하려는 경우 연관된 클래스도 함께 이해해야한다
` 와 파급 효과 라고 말씀해주신 부분이 엄청 공감되네요!!😃
역시 페퍼!!👍👍

2022-10-14 11:01 UTC, tco0427 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return execute(sql, preparedStatementSetter, preparedStatement -> {
도움이 되었다니 다행입니다ㅎ.ㅎ

2022-10-14 11:03 UTC, tco0427 approved these changes
안녕하세요 페퍼!!
바쁘신 와중에도 리뷰 반영 꼼꼼하게 해주셨네요👍👍
수고 많으셨습니다! 의견 나누는 과정 즐거웠습니다~_~

2022-10-14 11:03 UTC, merged