[JDBC 라이브러리 구현하기 - 2, 3단계] 어썸오(정수현) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #221
Opened 2022-10-11 04:44 UTC by awesomeo184

안녕하세요 판다~, 2단계에서 변경 사항이 좀 적어서 3단계와 함께 PR합니다. 잘 부탁드립니다~

2022-10-11 08:42 UTC, woong7 requested changes
안녕하세요 어썸오!
미션 잘 구현해 주셨네요. 
몇 가지 리뷰 남겨볼게요!!

2022-10-11 08:42 UTC, woong7 commented on app/src/main/java/com/techcourse/service/TxHandler.java
> +    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
TxUserService 구현체를 작성하는 대신, 리플렉션으로 메소드를 찾아서 주입해주는 방식으로 구현해 주셨네요. 
혹시 proxy 객체는 어떤 용도일까요? 

++ 스프링이 jdbcTemplate을 구현한 방식과 유사하게 구현해주신 걸까요?

2022-10-14 01:26 UTC, awesomeo184 commented on app/src/main/java/com/techcourse/service/TxHandler.java
> +    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
afee37e12832c8f6f41c277b83bb21cf78f1ba26

> ++ 스프링이 jdbcTemplate을 구현한 방식과 유사하게 구현해주신 걸까요?

그렇진 않고, `changePassword`외에 다른 부분에도 트랜잭션 기능을 추가하니 중복이 생겨서 다이나믹 프록시를 이용해 제거해봤습니다~

2022-10-14 01:27 UTC, awesomeo184 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        var conn = DataSourceUtils.getConnection(dataSource);
왠진 모르겠는데 `DataSourceUtils`를 사용하면 커넥션을 알아서 닫아주는걸로 착각하고 있었네요 ㅎㅎ;; 다시 수정하였습니다!

2022-10-14 01:34 UTC, awesomeo184 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      }
```java
    public <T> Optional<T> queryForObject(final String sql, final RowMapper<T> rowMapper,
                                          final PreparedStatementSetter pss) {
        return execute(sql, ps -> {
            pss.setValues(ps);
            return getSingleOrEmpty(new Extractor().extractResults(sql, rowMapper, ps));
        });
    }
```

이런 형태를 말씀하시는걸까요? 혹시 이유가 있을까요?

2022-10-14 02:28 UTC, woong7 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
>      }
아니요, ResultSetExtractor 같은 별개의 클래스를 만들어서 책임을 분리해보면 어떨까 하는 이야기였습니다!

2022-10-14 02:28 UTC, woong7 commented on app/src/main/java/com/techcourse/service/TxHandler.java
> +    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
어... 제가 이해를 잘 못하고 있는거 같은데요, 
해당 메소드에서 proxy 변수가 사용되지 않고 있는 것 같아서 여쭤봤습니다.

2022-10-18 01:18 UTC, merged