[JDBC 라이브러리 구현하기 - 3단계] 앤지(손수민) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #232
Opened 2022-10-11 07:42 UTC by soominsohn

안녕하세요 에덴! 마지막 미션이네요! ㅎㅎ 😄 
저번 단계에서 좋은 피드백 주셔서 감사해요 😄 
이번 미션에서는
- 트랜잭션 롤백이 적용되어 UserServiceTest 클래스의 testTransactionRollback() 테스트 케이스가 통과한다.
- 트랜잭션 서비스와 애플리케이션 서비스가 분리되었다.  

를 위주로 구현했어요.
그러면 이번 미션도 잘 부탁드려요 🙇

2022-10-11 16:09 UTC, leo0842 requested changes
안녕하세요 앤지! 에덴입니다 😄 

3단계도 빠르고도 깔끔하게 구현해주셨네요!!

로직 상은 크게 문제가 없어 보이지만 한번 생각해볼만한 부분에 대해 코멘트를 남겨 보았습니다.

반영할만하다고 생각하시면 반영해주시기 바랍니다 😉

2022-10-11 16:09 UTC, leo0842 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        userService.insert(user);
insert 에도 transaction 이 걸려야 할 것 같아요!!

그렇게 된다면 `changePassword` 메서드의 로직과 상당 부분 중복이 될 것 같은데, 이 중복될 부분도 줄여보면 좋을 것 같아요!

2022-10-11 16:09 UTC, leo0842 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        final Connection connection = DataSourceUtils.getConnection(dataSource);
connection 을 try-with-resources 바깥으로 빼서 connection 이 닫히지 않게 하셨네요!

여기서 connection 을 닫아버리면, `TxUserService` 에서 commit 또는 rollback 할 때 예외가 발생하여 미션의 기능 구현을 위해 이렇게 빼놓으신 것 같아요! 
하지만 이 connection 을 그냥 열린 채로 둬도 될까요 🤔

connection 을  close 하는 것 말고 또 다른 방식을 찾아보셔도 좋을 것 같습니당!!

2022-10-11 16:09 UTC, leo0842 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +                () -> verify(preparedStatement, times(1)).close()
꼼꼼한 테스트 본받고 갑니다 😄

2022-10-14 05:51 UTC, soominsohn commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        final Connection connection = DataSourceUtils.getConnection(dataSource);
`DataSourceUtils.releaseConnection`메서드가 있군요!
일단 finally로 처리해줬습니다! 새로운걸 알아가네요. 감사합니다 😄

2022-10-14 05:52 UTC, soominsohn commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        userService.insert(user);
다른 메서드도 transaction 걸어주고
함수형 인터페이스로 중복도 줄였습니다. 감사합니다 😄

2022-10-15 17:40 UTC, leo0842 approved these changes
안녕하세요 앤지! 에덴입니다 😄 

3단계 리뷰 반영해주신거 확인했습니다!!

이번 jdbc 미션 구현하느라 고생 많으셨습니다 🤸‍♂️

다음주부터 추워진다고 하니, 몸관리 유의하시면서 레벨 4 마무리 잘 하시길 바라겠습니다!!

2022-10-15 17:41 UTC, merged