[JDBC 라이브러리 구현하기 - 3단계] 찬(김찬) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #247
Opened 2022-10-11 09:26 UTC by kimchan123

2022-10-13 14:53 UTC, yh20studio requested changes
안녕하세요 찬 리뷰가 늦어져서 죄송합니다 😢
전반적으로 잘 구현해주셔서 좋았네요! 
몇가지 코멘트 남긴 부분에 대해서 확인해주시면 좋을 것 같아요
날씨가 추워졌는데 몸조리 잘하시길 바랍니다 화이팅!

2022-10-13 14:53 UTC, yh20studio commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementCallback.java
> +}
함수형인터페이스로 중복로직을 제거한게 좋네요!

2022-10-13 14:53 UTC, yh20studio commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var transactionManager = new DataSourceTransactionManager(jdbcTemplate.getDataSource());
DataSourceConfig.getInstance() 를 통해서 dataSource를 얻는 것은 어떨까요?

2022-10-13 14:53 UTC, yh20studio commented on app/src/main/java/com/techcourse/service/UserService.java
> +    User findById(final long id);
인터페이스의 정의된 함수의 매개변수에도 final을 선언할 필요가 있을까요?

2022-10-13 14:53 UTC, yh20studio commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
나머지 메서드에 대해서도 트랜잭션 적용을 해보는 건 어떨까요?

2022-10-14 05:37 UTC, kimchan123 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var transactionManager = new DataSourceTransactionManager(jdbcTemplate.getDataSource());
jdbcTemplate을 생성할 때 DatasourceConfig.getInstance()로 생성을 했는데요! 
`jdbcTemplate.getDataSource`와 `DataousrceConfig.getInstace()` 의 차이가 있나용? 궁금합니다!

2022-10-14 05:40 UTC, kimchan123 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    User findById(final long id);
명세를 정의하는 인터페이스에는 굳이 final을 선언할 필요가 없을 것 같아요!

2022-10-14 05:41 UTC, kimchan123 commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
insert와 findById에는 안걸고 있었네요.. 적용했습니다!

2022-10-14 05:44 UTC, kimchan123 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            final PreparedStatement pstmt = connection.prepareStatement(sql);
TransactionManager에서 transaction이 종료되면 connection이 자동으로 release 되는 것으로 알고 있습니다!

2022-10-16 04:01 UTC, yh20studio commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +        final var transactionManager = new DataSourceTransactionManager(jdbcTemplate.getDataSource());
차이는 크게 없으나, JdbcTemplate에서 getDataSource 메서드가 테스트에서만 사용되는 것을 볼 수 있어서 굳이 이용도로 정의할 필요는 없었다고 느낀 것 같아요! 그런데 사실 동작하는데 차이가 없으니 크게 반영하지 않아도 될 거 같아요!

2022-10-16 04:01 UTC, yh20studio approved these changes
코멘트 달아주시고 리뷰 반영해주신점 확인했습니다!
이번 미션 고생 많으셨습니다~

2022-10-16 04:01 UTC, merged