[JDBC 라이브러리 구현하기 - 1, 2단계] 수리(이다원) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #29
Opened 2021-09-24 15:48 UTC by DWL5

안녕하세요! 시드! 이번에 코드리뷰를 받게 될 수리입니다.

스프링의 JdbcTemplate를 참고해서
PreparedStatementCreator, PreparedStatementCallback을 통해
다양한 처리를 할 수 있도록 구현해 보았습니다!!

아직 템플릿 메소드 패턴과 콜백 개념이 익숙치 않아 어려웠습니다!!
그럼 코드리뷰 부탁 드릴게요!!
감사합니다 시드!

2021-09-26 11:25 UTC, hsik0225 requested changes
### 안녕하세요 수리
템플릿 메소드 패턴과 콜백 패턴을 공부하시고 적용하시느라 수고 많으셨습니다!
위의 패턴을 이용해서 중복없고 깔끔한 코드를 작성하시려고 노력하신 게 코드에서 보였네요 👍

몇몇 수리의 코드에 대한 저의 생각을 적어보았어요.
확인해주시고 리뷰 요청 부탁드릴게요!

2021-09-26 11:25 UTC, hsik0225 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        log.debug("insert : {}", user);
로그를 찍어서 어떤 파라미터가 들어왔는지 확인하는 것 좋네요 👍

2021-09-26 11:25 UTC, hsik0225 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +                result.add(rowMapper.mapRow(resultSet, i));
UserDao에서 RowMapper 구현 메소드인 userRowMapper()를 살펴보니 RowMapper의 파라미터인 rowNumber가 사용되지 않는 것 같은데, 따로 넣어두신 이유가 있을까요??

```java
private RowMapper<User> userRowMapper() {

    // `rm`이 사용되지 않음
    return (rs, rm) -> new User(
            rs.getLong(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4)
    );
}
```

2021-09-26 11:25 UTC, hsik0225 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private <T> T execute(PreparedStatementCreator preparedStatementCreator, PreparedStatementCallback<T> action) {
콜백 패턴을 써서 코드가 재사용이 많이 되고 깔끔하네요 👍

2021-09-27 07:09 UTC, kang-hyungu requested changes
수리 간단한 피드백 남겼으니 참고하세요

2021-09-27 07:09 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(connection -> {
1. connection을 라이브러리 사용자에게 노출할 필요가 있을까요?
2. update 메서드도 가변인자를 추가해서 사용자가 좀더 사용하기 좋게 만들면 어떨까요?

2021-09-27 07:09 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void setDataSource(DataSource dataSource) {
setter 사용 금지 입니다

2021-09-27 07:09 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            ResultSet resultSet = preparedStatement.executeQuery();
ResultSet은 close 처리를 안하고 있는데 관련 처리를 추가해보아요

2021-09-27 08:13 UTC, DWL5 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        });
이번 미션은 예전 지하철 미션을 참고하면서 진행 해보았습니다!

update문이 아래와 같이 되어있어서 update문은 직접 PreparedStatementCreator의 구현체를 전달하는 식으로 했는데
getArgumentPreparedCreator를 사용하도록 변경하였습니다.

```
 jdbcTemplate.update(con -> {
            final PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setLong(1, lineId);
            pstmt.setLong(2, section.getUpStationId());
            pstmt.setLong(3, section.getDownStationId());
            pstmt.setInt(4, section.getDistance());
            return pstmt;
        });
```

c99c9d6에 반영했습니다.

2021-09-27 08:24 UTC, DWL5 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    }
Spring의 JdbcTemplate를 참고하여 만들다 보니 setter를 두었네요
이번 미션에서는 굳이 필요없는데 들어갔습니다 ㅜ
밑에 구구 피드백도 setter 사용금지라고 하셔서 지우겠습니다!

cc6439c

2021-09-27 08:25 UTC, DWL5 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return null;
EmptyResultDataAccessException를 던지도록 수정해보았습니다!

912be37

2021-09-27 08:30 UTC, DWL5 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +                result.add(rowMapper.mapRow(resultSet, i));
RowMapper 또한 Spring 프레임워크의 RowMapper를 참고해서 구현해보았습니다.
rm에는 Row의 개수가 담깁니다.

현재 사용되고 있지는 않지만,
JDBC쪽이 라이브러리 형태로 제공되고 있으니, 해당 기능은 제공해주는것도 나쁘지 않아보여요!

2021-09-27 08:31 UTC, DWL5 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            ResultSet resultSet = preparedStatement.executeQuery();
d4da350
try-with-resource로 처리 해보았습니다~

2021-09-27 08:32 UTC, DWL5 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public void setDataSource(DataSource dataSource) {
cc6439c 반영했습니다!

2021-09-27 08:32 UTC, DWL5 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        jdbcTemplate.update(connection -> {
c99c9d6
반영 했습니다!

2021-09-27 08:34 UTC, DWL5 commented
시드, 구구 좋은 피드백 감사합니다!!
피드백 반영해보았습니다~ 😀

2021-10-01 08:51 UTC, hsik0225 approved these changes
안녕하세요 수리!!
빠르게 구현해주셨는데 리뷰가 늦어 죄송합니다 😅
구구가 남겨주신 피드백 반영까지 확인했습니다!

이번 미션은 여기서 머지할게요, 수고하셨어요!

2021-10-01 08:51 UTC, merged