[JDBC 1단계] 키아라 미션 제출합니다
woowacourse/jwp-dashboard-jdbc pull request #292
Opened 2023-09-27 09:32 UTC by kiarakim

케로케로케🐸 안녕하시렵니까. 키아라입니다.🦁

JDBC 라이브러리 구현해서 코드 리뷰 요청드립니다.
혹시 테스트가 부족하거나 요구사항을 충족하지 못한 부분이 있으면 알려주세요.

감사감사 미리감사😉

즐거운 추석 보내시구, 즐거운 코드리뷰... 홧팅><

2023-10-01 12:47 UTC, jyeost requested changes
안녕하세여 키아롸라라라라라라라><
연휴는 잘 보내고 계신가여?!?!?!?!?!!  히히히
제가 저번주를 날려먹어서... 지난 미션 똥을 치우느냐 리뷰가 늦었습니다... 죄송쬐쏭...

코드 깔끔하게 잘 짜주셔서 많이 배워갑니다... (--)(__)=bb
큰 변동 사항은 아니지만 이번 단계에서 짚고 갔으면 좋겠는 부분이 있어서 
request change 남깁니다... ! 
답변주시고 리뷰요청 부탁드립니다 !!!!!!!!!!

2023-10-01 12:47 UTC, jyeost commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        return results.get(FIRST_RESULT_INDEX);
만약 query의 결과가 비어있다면 어떻게 되나용?

2023-10-01 12:47 UTC, jyeost commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        if (rs.next()) {
if문을 사용해도 괜찮나요??

2023-10-01 12:47 UTC, jyeost commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    private static void setObjects(Object[] args, PreparedStatement preparedStatement) throws SQLException {
함수를 static으로 써준 이유가 있나요?

2023-10-01 12:47 UTC, jyeost commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +            new User(
static 필드 좋네여 !!!
이 부분을 고민 하고 있었는데 파쿠리 해야겠서여 >< ㅎㅎ

2023-10-01 12:47 UTC, jyeost commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +                    rs.getString("email")
필드도 명확한거 좋네용 :)

2023-10-03 05:35 UTC, kiarakim commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        return results.get(FIRST_RESULT_INDEX);
빈 객체가 넘어가겠지요. 
그런데 그렇게 의미없는 반환을 하는 것 보단 예외처리를 해주는 게 좋을 것 같네용ㅎㅎ

2023-10-03 05:35 UTC, kiarakim commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        if (rs.next()) {
if를 사용하면 안된다는 뜻일까요?
생각해보니 ResultSet은 Statement 객체로 SELECT 문을 사용해서 얻어온 레코드들 테이블 형태로 갖고오는건데 if 문을 하면 하나의 레코드만 갖고오는 것 같고.. 그래서 while이 좋은 것 같기도 하고.. 어우 어려워
질문이 어떤 의도인지 잘 모르겠아요! 일단 while로 바꾸겠습니당

2023-10-03 05:35 UTC, kiarakim commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    private static void setObjects(Object[] args, PreparedStatement preparedStatement) throws SQLException {
앖아용!
자동 메서드 추출하면서 static이 붙은 것 같아유. 매의 눈 감사합니다

2023-10-04 02:38 UTC, jyeost commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        return results.get(FIRST_RESULT_INDEX);
놀랍게도... IndexOutOfRangeException 이 발생한답니다 !! 
수정한 식에서도 발생할 거에여... 그러니 사이즈를 검증하는게 좋겠조?!

2023-10-04 02:41 UTC, jyeost commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        if (rs.next()) {
말씀해주신대로 rs객체 안에 결과가 전부 담겨있고 
rs.next()를 사용하면서 커서를 하나씩 이동하는 거여용!!
while을 써서 다음 행이 없을때까지 전부 조회해야 모든 raw 를 조회할 수 있습니당 !!
이전 식에서는 List이긴 하지만 사이즈가 전부 1이였을 거에여ㅎㅎ

2023-10-04 02:48 UTC, jyeost approved these changes

2023-10-04 02:48 UTC, merged