[JDBC 라이브러리 구현하기 - 1단계] 마코(이규성) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #310
Opened 2023-09-28 12:12 UTC by aak2075

안녕하세요 스플릿! 마코입니다~😄

스플릿을 마지막으로 모든 온보딩 조원과 페어, 미션을 진행했네요ㅎㅎㅎ

일단은 요구 사항만 충족시키도록 구현했습니다.

무언가 더 해보고 싶지만 어렵기도하고 2단계가 리팩터링이라 다음 단계로 미루겠습니다.

즐거운 추석 보내세요~~🌕

2023-09-29 18:28 UTC, splitCoding requested changes
마코!!😁 

추석 잘 보내고 계신가요ㅎㅎ🙇

캠퍼스 갈린후로 거의 못봤는데 리뷰로 만나네요ㅎㅎ👍

개인적으로 고민을 많이 한 미션인데 비슷한 고민을 한거 같은 부분도 있고 훨씬 간단하게 풀어낸 부분도 있어서 저한테도 도움이 많이 되는 리뷰였어요!!💪

1단계 미션 요구사항은 충분히 반영되어 있다고 생각합니다!!

의견을 묻는 코멘트 2개정도 있는데 이부분에 대해서 답변해주시고 리뷰 요청주시면 바로 머지하도록 하겠습니다!!

수고많았어요 🎁

2023-09-29 18:28 UTC, splitCoding commented on jdbc/src/main/java/org/springframework/jdbc/core/PreparedStatementSetter.java
> +public interface PreparedStatementSetter {
확장성을 위한 추상화 👍

2023-09-29 18:28 UTC, splitCoding commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            }
마코가 현 1단계 미션에서 rowNum 이 포함된 코드를 작성해야겠다고 결정한 이유가 궁금해요😊

2023-10-01 02:27 UTC, aak2075 commented on jdbc/src/main/java/org/springframework/jdbc/core/ArgumentPreparedStatementSetter.java
> +public class ArgumentPreparedStatementSetter implements PreparedStatementSetter{
저는 argument 기반의 PreparedStatementSetter라고 생각을 해서 ArgumentPreparedStatementSetter라고 지었습니다.
확실히 스플릿이 말씀해주신 PreparedStatementArgumentSetter가 의미 전달이 잘 되는 것 같습니다👍
하지만 나중에 PreparedStatementSetter 뿐만 아니라 PreparedStatementCreator와 같이 비슷한 이름의 여러 인터페이스가 생기는 경우 헷갈릴 것 같아 가능하면 인터페이스의 이름을 사용하는 것이 좋다고 생각합니다~

2023-10-01 02:27 UTC, aak2075 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            }
페이징 쿼리와 같은 확장성을 생각했었는데 사실 지금 생각해보니 구현도 안됐고, 할지 안할지도 모르는 상태에서 짧은 생각으로 넣었던 것 같네요! 복잡도만 높이는 요인인 것 같아 일단 제거하고 나중에 필요할 때 추가하겠습니다~

2023-10-01 05:18 UTC, merged