[JDBC 라이브러리 구현하기 - 1, 2단계] 춘식(안예장) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #32
Opened 2021-09-25 18:07 UTC by RinSabbit

안녕하세요 루트~~ 요즘 대화를 거의 못해본 거 같은데 리뷰어로 만나게 되어서 너무 반갑네요!!!! 잘 부탁드립니다!!!
요구사항은 며칠 전에 끝냈는데... 테스트도 열심히 짰는데...!!
어플리케이션을 실행하니까 (제 추측으로는) userDao가 자동주입이 안 되어서 에러가 나는 것 같더라구요 🥲
야심차게 어노테이션을 만들어가지고 해결하려다... 잘 안 되어서 제출 먼저 해봅니당 흑흑
계속 건드리는 중인데 해결된다면 커밋하고 디엠 드릴게요 😇 
피드백은 환영이에요!!!!

2021-09-27 06:00 UTC, Junroot requested changes
![image](https://user-images.githubusercontent.com/4648244/134847500-a2c5dd6e-f66c-46ee-b450-279b1c99ec04.png)

현재 애플리케이션 실행해보니 `users` 테이블이 생성이 안되고 있네요 😢
애플리케이션 실행할 때, `scheme.sql`이 실행되도록 수정해야될 것 같아요!

2021-09-27 06:20 UTC, RinSabbit commented on app/src/main/java/com/techcourse/controller/LoginController.java
> +            final User user = userDao.findByAccount(request.getParameter("acccount"));
어cccㅏ운트 수정

2021-09-27 06:28 UTC, RinSabbit commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
> +                    .orElseThrow();
단수로 궈궈

2021-09-27 06:28 UTC, RinSabbit commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
> +    Reflections daoReflections = new Reflections("com.techcourse.dao");
호다닥 지웠습니다

2021-09-27 06:37 UTC, RinSabbit commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public int insert(User user) {
[jdbcTemplate 공식 문서](https://view.live1month.com/accommodations/2054)에서 int를 반환하길래 참고해봤습니다!!

2021-09-27 07:13 UTC, kang-hyungu commented
루트가 피드백 잘 남겨주셨네요 👍🏻

2021-09-28 02:39 UTC, RinSabbit commented on mvc/src/main/java/nextstep/mvc/controller/tobe/ControllerScanner.java
> +        return daoClass.getDeclaredConstructor().newInstance();
ControllerScanner가 Repository 클래스를 맵으로 가져서 맵을 통해 같은 인스턴스를 공유하도록 했습니다!!

2021-09-28 11:09 UTC, Junroot commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public int insert(User user) {
개인적으로는 `JdbcTemplate`에서 int를 반환하는 것은 라이브러리의 의도로 동의를 해요.
그런데 `UserDao`는 비즈니스 로직 상 사용하지 않는데 불필요하게 반환하고 있다는 생각이 드네요.
이 부분은 취향의 영역이라고 생각이 들어, 굳이 한번더 수정 요청은 하지 않겠습니다!!

2021-09-28 11:20 UTC, Junroot commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            rs.close();
`ResultSet`도 Try-with-resources를 사용해보는 건 어떨까요?

2021-09-28 11:20 UTC, Junroot commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private interface Execute<T> {
`Execute`를 `JdbcTemplate`에서만 사용가능하도록 하기 위한 의도면 이해가 되네요! 동의합니다!

2021-09-28 11:29 UTC, Junroot requested changes
안녕하세요 춘식! 
대부분 피드백을 잘 반영해주셨네요! 
마지막으로 딱 하나만 더 확인해주시면 좋겠어요!
DB 테이블을 생성하지 못하던 문제는 제가 IntelliJ로 빌드하니 정상적으로 실행되어서 신경쓰지 않아도 될 것 같아요!

2021-09-28 11:29 UTC, Junroot commented on app/src/main/java/com/techcourse/config/DataSourceConfig.java
> +            INSTANCE = createHikariDataSource();
배운 걸 배로 적용하다니 멋져요!

2021-09-28 11:29 UTC, Junroot commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            rs.close();
`ResultSet`도 Try-with-resources를 사용해보는 건 어떨까요?

2021-09-29 02:07 UTC, RinSabbit commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    public int insert(User user) {
취향을 개조해봤습니다

2021-09-29 02:08 UTC, RinSabbit commented
루트 피드백 반영했워요!!!
인텔리제이가 문제였군요 흑흑흑 그저 눈물만 😂 
확인 부탁합니다 꾸벅꾸벅

2021-09-29 02:40 UTC, Junroot approved these changes
피드백 빠르게 반영해주셨네요! 
이번 미션은 여기서 merge 하겠습니다!👍
춘식의 코드를 리뷰하고, inner class를 언제 사용하면 좋을지 생각해보게 되는 좋은 기회가 있어서 좋았어요!

2021-09-29 02:40 UTC, merged