[JDBC 라이브러리 구현하기 - 2단계] 포이(김보준) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #342
Opened 2023-09-30 13:35 UTC by poi1649

베로 안녕하세요! 어느덧 연휴의 절반이 지나가고 있네요.
매년 느끼지만, 대보름즈음의 달은 몇 번 봐도 질리지도 않게 예쁘지 않나요? 
일년에 한 번 있는 날인만큼 바쁘시더라도 여유를 갖고 밤하늘을 보며 산책하는 시간을 가져보시는건 어떠신가요!? (한가위 다음 날 미션을 제출하며)

---

1단계에서 모든 메서드가 CheckedException을 반환하지 않도록 하였고, 또 이에 대한 처리 로직을 한 군데로 몰아 관리지점을 최소화할 수 있도록 코드를 작성했습니다. 이와 더불어 1단계에서 비즈니스외의 로직은 JDBCTemplate 모듈이 관리할 수 있도록 하였기 때문에 이번 단계에서는 큰 수정이 없었네요!

정말 아무 수정도 없이 내는 것 같아 Transaction 에 대해 공부하여 이를 관리하는 책임을 작성해볼까 했는데 3단계에 있길래 그대로 놔뒀습니다. 또, 그럼 커넥션 풀 이라도 만들어볼까 했는데 이것도 4단계에 있길래 그대로 남겼습니다.🤦‍♂️

혹시 제가 2단계에서 놓치고 가는 부분이 있다면 베로가 잡아주시길 바라며 미션을 제출해봅니다.

++남은 연휴도 좋은 시간 되시길 바랍니다!🙆‍♂️

2023-10-02 13:09 UTC, Cyma-s requested changes
안녕하세요 포이~
1단계를 잘 구현해주셔서 그런지 제가 아무리 눈을 크게 뜨고 찾아봐도 고쳐야 할 부분을 찾기가 너무 어렵더라고요..... 코드를 15번은 넘게 본 것 같은데 😅
큰 변화는 아니지만, 포이 의견이 궁금한 부분들이 있어서 Request Change 드렸습니다 🙂

편하실 때 반영해 주시고 다시 리뷰 요청 주세요 ! 🚀

2023-10-02 13:09 UTC, Cyma-s commented on app/src/main/java/com/techcourse/dao/UserDao.java
위쪽이 댓글이 안 달려서 여기에 씁니다 :)
`RowMapper` 의 `getLong`, `getString`을 할 때, 결과값을 행의 순서로 가져오지 않고, 컬럼의 이름으로 가져오는 건 어떠신가요?
현재 구조 상에서는 개발자가 select 문을 사용할 때 주의를 기울여서 작성해야 할 것 같아요. 그 과정에서 실수가 있으면 다른 값이 들어갈 수 있을 거라 생각합니다. 컬럼 이름으로 가져오면 개발자의 부주의로 인한 실수를 좀 더 막을 수 있지 않을까 싶습니다 🙂

2023-10-02 13:09 UTC, Cyma-s commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>      @Test
DataSource 나 Connection 선언은 `@BeforeEach` setup 메서드로 분리할 수 있을 것 같은데 어떤가요?

2023-10-02 13:09 UTC, Cyma-s commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>      }
리스트를 리턴하는 query 의 경우에도 검증 테스트가 있다면 더 좋을 것 같아요 :)

2023-10-02 13:53 UTC, poi1649 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e.getSQLState());
사용자에게 CheckedException인 SQLException을 던져주는 대신, UncheckedException으로 변환해주기 위함입니다! 예외의 정보는 유지하기 위해 정보를 함께 담아주었습니다

2023-10-02 13:59 UTC, poi1649 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>          execute(sql, new PreparedStatementCreator(), ps -> {
doc을 확인해보니 jdbc에서 execute 같은경우 DDL을 실행하는 데 사용하는 것을 권장하고, 
그 외 dml 문은 update를 사용하는 것을 권장한다고 합니다. 
만약 ddl이라면, results를 변화한 행 수처럼 측정할 수 없겠죠? (당연히 어떤 결과도 반환하지 않을 것이기 때문에)
때문에 execute 같은 경우는 검증을 하지 않도록 하였습니다! 
밑은 스프링 jdbc doc 캡쳐본입니다!

<img width="492" alt="image" src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/74969077/56dbd81b-6551-4b51-a5f2-0e0d18e3d39d">

<img width="556" alt="image" src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/74969077/1846294d-c02a-4a03-bc50-64d5525ca8b6">

2023-10-02 14:11 UTC, poi1649 commented on app/src/main/java/com/techcourse/dao/UserDao.java
엇 resultSet에서 컬럼 라벨에서 행을 가져올 수 있다는 것을 머리털나고 처음 알았네요. 미세한 성능적 단점은 존재하지만 신뢰성을 보장해줄 수 있어서 성능 튜닝이 필요하지 않다면 라벨을 사용하는 것이 확실히 좋을 것 같아요!
관련해서 일반 개발자들은 무엇을 왜 선호할까 찾아보았는데 답변들이 웃겨서 공유합니다 ㅋㅋㅋ

[스택오버플로우 관련 질답](https://stackoverflow.com/questions/186799/resultset-retrieving-column-values-by-index-versus-retrieving-by-label)

2023-10-02 14:14 UTC, poi1649 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>      @Test
좋아용 ̼

2023-10-02 14:23 UTC, poi1649 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>      }
지금보니 테스트가 많이 이상하네용 
rowMapper를 제외한 나머지를 잘 검증할 수 있도록 수정했습니다!

2023-10-02 14:27 UTC, Cyma-s commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>          execute(sql, new PreparedStatementCreator(), ps -> {
확실히 ddl 의 경우를 생각해보면 정상 동작인데 null 인 경우가 충분히 있을 것 같네요! 좋은 답변 감사합니다 👍👍👍👍

2023-10-02 14:33 UTC, Cyma-s commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e.getSQLState());
미션에서 요구한 사항을 잘 충족해주셨네요 👍
그렇다면 혹시 `e.getMessage` 가 아닌 `e.getSQLState` 만 전달하는 이유는 어떤 거였나요??

2023-10-03 05:39 UTC, poi1649 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException(e.getSQLState());
앗, SQLState로 자세한 예외의 클래스를 나눠주는게 아니면 확실히 getMessage를 쓰는 편이 낫겠네요! 수정하였습니다

2023-10-05 04:59 UTC, Cyma-s approved these changes
안녕하세요 포이~
요구사항 잘 반영해주셨네요 👍👍👍 이번 단계에서 충족해야 하는 요구사항들은 다 만족한 것 같아 어프루브하겠습니다 :)

날씨 추운데 감기 조심하세요
3단계 미션 가보시죠 🚀🔥

2023-10-05 05:00 UTC, merged