[JDBC 라이브러리 구현하기 - 2단계] 우르(김현우) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #343
Opened 2023-09-30 15:02 UTC by java-saeng

안녕하세요 히이로 !!
이전 단계에서의 리뷰 잘 봤습니다

제가 생각과 비슷하셔서 코멘트 읽는데 재밌었습니다.
저는 그냥 `이 부분 힘들겠다`라며 마음 속으로만 생각하고 지나갔는데, 코멘트를 통하여 작성된 글을 보니 또 다르더라구요,,

그 불편한 부분이 대부분 객체 반환 부분이었는데, LMS에 있는 힌트를 보고 재밌게 구현해보았습니다.

이번 미션도 잘 부탁드립니다!

2023-10-01 18:23 UTC, MoonJeWoong requested changes
안녕하세요 우르, 2단계 잘 구현해주신 것 잘 봤습니다! 

최대한 간소하게, 하지만 필수적인 부분은 잘 리팩토링 되었다는 생각이 들었던 것 같아요.
LMS의 힌트를 보고 의미있는 리뷰를 드려볼 수 있을까 싶었는데... 제가 jdbcTemplate을 보면서 구현을 해버린지라 저한테는 크게 와닿지는 않더라구요 ㅎㅎ... 

대신 제가 받았던 리뷰나 다른 크루들 리뷰에서 봤던 내용들을 토대로 현재 우르 코드에서 좀 더 개선해볼만한 부분들을 리뷰하는데 집중해봤습니다. 혹시 얘기 나눠보고 싶으신 사항들이 있다면 코멘트나 DM으로 편하게 메세지 남겨 주세요!

2023-10-01 18:23 UTC, MoonJeWoong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        }
ResultSet도 꼼꼼하게 close 해주시기 위해 try-with-resource를 적용해주셨네요! 👍 

그런데 ResultSet 인터페이스는 생성된 Statement 객체가 close 될 때 함께 close 된다고 합니다. 해당 내용은 ResultSet 인터페이스에 명시된 close() 메서드 주석 부분을 참고해보시면 좋을 것 같습니다. 저도 다른 크루들 리뷰를 통해 알게된 내용이었는데 공유드려요~ ㅎㅎ

![image](https://github.com/woowacourse/jwp-dashboard-jdbc/assets/31722737/41cfa8c3-4c34-48cb-b1a2-a6e9ad54c308)

2023-10-01 18:23 UTC, MoonJeWoong commented on jdbc/src/main/java/org/springframework/jdbc/core/RowMapper.java
> +@FunctionalInterface
잊지 않고 챙겨주신 부분 좋습니다 👍

2023-10-01 18:23 UTC, MoonJeWoong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +          return rowMapper.map(resultSet);
해당 query() 메서드는 단일 객체를 반환하는 쿼리를 수행할 때 사용될 것 같습니다. 그런데 만약 사용자가 결과 값이 2개 이상인 조회 쿼리를 이 query 메서드를 통해 수행하게 된다면 어떻게 될까요? 지금은 조회 결과가 2개 이상이어도 첫번째 조회 결과값만 반환되고 나머지는 무시되면서 정상 동작하게 됩니다. 

라이브러리 입장에서 이런 사용자의 오용 가능성을 방지하기 위해 어떻게 해줄 수 있을지 고민해보시면 좋을 것 같습니다 ㅎㅎ

2023-10-01 18:23 UTC, MoonJeWoong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        return results;
pstmt.executeQuery()의 결과인 ResultSet의 row들을 추출하는 역할의 메서드를 분리해보시는 건 어떠신가요? query() 메서드에서도 비슷한 로직을 사용하는데 이를 활용해보면 query() 메서드에서도 리팩토링할 부분이 생길 수 있을 것 같습니다! (사용자의 쿼리 오용 예외처리, null 값 반환 제거 등...)

2023-10-02 06:54 UTC, java-saeng reviewed
[코멘트 링크](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/314)

> 물론 mock 테스트를 작성하다 보면 당연한 부분이겠지만서도 혹시 우르는 다른 방식으로 테스트를 생각해보셨을까? 하는 부분에서 질문드린 것이었습니다!

아하,, 그렇군요

저는 현재 UserDao에서 하는 테스트를 `통합 테스트`라고 생각이 들어서 굳이 `JdbcTemplate`에서의 테스트가 필요한가라는 생각을 해서 따로 생각해보진 않았어요

근데 히이로의 말씀을 듣고, 이런 라이브러리들은 어떻게 테스트를 작성하면서 개발할까? 라는 의문이 들긴하네요.
테스트를 작성하지 않을 수도 있고, 히이로처럼 `JdbcTemplate`에서 단위테스트를 진행할 수 있을 것 같습니다.

제 의견을 말씀드리자면 `JdbcTemplate`에서 무엇을 테스트하고 싶은가? 에 대해 의문이 생깁니다.
UserDao에서의 테스트로 충분히 커버할 수 있다는 생각이 들어서요.

JdbcTemplate 로직을 작성하는 것을 보면 테스트 할 것이 DataSource가 잘 동작하나, Connection을 잘 얻어오는가, PreparedStatement가 잘 동작하는가, PreparedStatement에 값들이 잘 맵핑 되는가? 그런 부분들을 테스트하는 것 같아서요.

그래서 충분히 .UserDao에 있는 테스트를 통해서 커버가 가능하지 않을까라는 조심스러운 의견을 내봅니다!

2023-10-02 06:54 UTC, java-saeng commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +          return rowMapper.map(resultSet);
오.. 이것까지 생각 못했는데 사용자 입장에서는 잘못 사용할 수 있겠네요,,

query 메서드를 실행할 때는 단일 값만을 조회하도록 메서드를 변경시켜보았습니다

2023-10-02 06:54 UTC, java-saeng commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        return results;
메서드를 extract하니까 null 반환이나 사용자 오용을 막을 수 있을 것 같아요,!!

좋은 리뷰 감사합니다 :)

2023-10-02 15:31 UTC, MoonJeWoong approved these changes
안녕하세요 우르! 깔끔하게 리뷰 반영해주셔서 Approve하도록 하겠습니다.
남겨주신 의견도 잘 봤습니다 :) 이제 3단계 미션 진행하러 가시죠~ 🚀

2023-10-02 15:31 UTC, MoonJeWoong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +      validateResultSizeIsSingle(result);
👍

2023-10-02 15:31 UTC, merged