[JDBC 라이브러리 구현하기 - 1, 2단계] 와이비(허영범) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #39
Opened 2021-09-26 15:52 UTC by hybeom0720

안녕하세요! 아마찌
리뷰이로 오랜만에 뵙게 되었습니다.
이번 미션은 앞선 두 미션에 비해 난이도가 상당히 높았던 것 같습니다.
추석 기간 내내 지속적으로 조금씩 조금씩 공부하면서 진행하게 되었어요.
특히나 프레임워크가 알아야할 범위는 어디까지인가?를 많이 고민해볼 수 있었던 것 같습니다.
가이드라인을 따라가다보니 궁금한 점이 생겨서 같이 질문으로 남기겠습니다.

1) JDBCTemplate Test
jdbctemplate은 라이브러리에 속해져있습니다. 때문에 외부의 구조를 알면 안되는데요.
이 때문에 테스트 코드를 진행할 때, verify를 통해서 해당 구성요소들이 동작을 하느냐 안하느냐 정도만 알 수 있었던 것 같습니다.
컴포넌트로 하나의 요소이며, 어떤 값을 반환할지 모른다는 점에서 이정도면 충분한 테스트라고 추론을 하고 있는데 아마찌의 의견이 궁금합니다.

2) PreparedStatementSetter
값을 삽입하는 insert 로직은 PreparedStatement에서 setValue를 해줄 필요가 없습니다.
이 때문에 따로 인터페이스로 분리를 하면 좋겠다고 가이드라인에 나와있었는데요.
하지만 setValue를 어떻게 분리하면 좋을지, 더 나아가 가변인자로 인해서 자동으로 생략이 될 것 같은데 분리 필요성이 큰지 궁금해서 질문을 남기게 되었습니다.

감사합니다!

2021-09-27 07:49 UTC, kang-hyungu requested changes
와이비 간단한 피드백 남겼으니 참고하세요

2021-09-27 07:49 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +            if (resultSet.next()) {
라이브러리 사용자가 직접 if절 처리를 하려면 번거롭겠네요
라이브러리 내부에서 처리해줄 수 있지 않을까요?

2021-09-27 07:49 UTC, kang-hyungu commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.queryObjectWithCondition(sql, rowMapper, id);
queryObjectWithCondition 메서드명이 너무 기네요
자바는 강타입 언어기 때문에 메서드 리턴 타입을 보고 condition 부분을 충분히 알 수 있으니 저부분은 제외해도 되지 않을까요?

2021-09-27 07:49 UTC, kang-hyungu commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        ResultSet resultSet = preparedStatement.executeQuery();
ResultSet의 close 처리가 안보이는데 이부분 추가해보아요

2021-09-27 09:07 UTC, NewWisdom requested changes
안녕하세요 비와이 ~ 🙋‍♀️
이렇게 미션 리뷰어로 만나뵙게되니 진짜 반가워요 ㅎㅎㅎ 
이번 미션 정말 잘 진행해주셨네요 짱짱 👏👏
미션 요구사항의 이외의 부분들도 구현하시고... 멋집니다 !!

잘 구현해주셔서 피드백을 크게 남길 부분이 없었지만, 
보면서 몇가지 코멘트와 비와이의 고민에 대한 제 생각을 남겨보았으니 
확인해보시고 와이비의 취향대로 반영하시면 될 것 같습니다 !

미션 진행하시느라 수고많으셨어요. 코드보면서 많이 배워갑니다.
화이팅 🔥

2021-09-27 09:07 UTC, NewWisdom commented on app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
> +@ConnectingDB
어노테이션을 통한 주입 짱이네요...
감탄하고 갑니다 짱짱 👏

2021-09-28 12:20 UTC, hybeom0720 commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
>          final User user = new User("gugu", "password", "hkkang@woowahan.com");
리팩토링하면서 해당 기능을 수정하였는데, 테스트엔 반영을 못했었네요 ㅜㅜ 
꼼꼼한 리뷰 감사드립니다.

2021-09-28 12:29 UTC, hybeom0720 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>  class JdbcTemplateTest {
앗! 테스트용 객체를 만드는 방법도 있었군요!
확실히 단순히 작동을 한다 안한다로 플로우만 체크하는 것이 아닌, 테스트에서 객체를 통해 테스트하는 것이 원하는 결과물이 나오는 것까지 확인 가능할 것 같습니다. 
좋은 의견 감사합니다!

2021-09-28 12:54 UTC, hybeom0720 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    }
앞의 리뷰에 대한 생각을 말씀드리자면,
중복된 아이디로 가입하면 문제가 생기는 것을 보이기 위해서 해당 로직을 넣게 되었어요.
선배 개발자 (리뷰어분들) 이나 크루들도 의견이 조금 갈리는 부분 때문입니다.

예를 들어 중복 아이디 체크는 DB에 질의를 해주고, 가입을 할 것인가 
아니면 DB에서 중복된 아이디로 회원가입을 시도하면 나오는 오류를 잡아서 회원가입 실패를 알릴 것인가?
라는 것으로 DB에 비즈니스 로직을 위임할 것인가에 대한 문제입니다.

많은 크루들과 리뷰어분들 이야기를 들으면서, 저는 전자에 조금 더 좋다고 생각을 했습니다.
왜냐하면 DB를 확인하지 않고도 자바만으로 로직을 추론할 수 있는 방법이 좋다고 생각했어요.
하지만 대용량 데이터를 다룰 때는 전자의 경우에는 SQL을 두번 날려서 디비에 부하가 많이 걸리니, 후자도 나쁘지 않는 방법이다. 라는 의견을 듣게 되었고 한 번 반영을 여기서 해보게 되었습니다.
아마찌의 리뷰를 보고 나서, 각각의 방법에 대해서 다시 생각을 하게 되는 것 같습니다. 오류를 잡아주는 AOP라던지 많은 보강이 필요해보이네요. ㅎㅎ 좋은 질문 감사드립니다.

2021-09-28 20:40 UTC, NewWisdom approved these changes

2021-09-28 20:40 UTC, NewWisdom commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
if문 처리도 개선하셨군요 👏

2021-09-28 20:40 UTC, NewWisdom commented on jdbc/src/main/java/nextstep/jdbc/ObjectMapper.java
> +public class ObjectMapper {
ObjectMapper, PrepareStatementSetter 분리 👏👏
Jackson의 ObjectMapper와 이름이 같으니 
개인적으로는 해당 클래스의 네이밍을 다르게 가져가도 좋을 것 같아요 ㅎㅎ

2021-09-28 20:47 UTC, NewWisdom commented on app/src/main/java/com/techcourse/service/UserService.java
> +    }
오 좋은 고민입니다. 
디비 제약조건으로 인해 이제 회원 중복 가입을 방지하겠군요 !
와이비의 고민에 그냥 제 의견을 얹어보면 
저는 애플리케이션에서만으로도 우리의 비즈니스 로직의 예외를 확인할 수 있게,
또 DB에도 해당 제약조건을 걸어주는 것을 선호합니다 ㅎㅎ
역시 비와이굳 👏

2021-09-28 20:53 UTC, NewWisdom approved these changes
안녕하세요 와이비 👻
미션 진행하고 피드백 반영하시느라 수고 많으셨어요.
와이비 코드를 리뷰하면서 저도 많이 배워갑니다 🙇‍♂️
미션을 진행하면서의 와이비의 고민과 의견을 들으면서 저도 다양한 인사이트를 얻고 갑니다.
수고 많으셨습니다 !
남은 과정도 화이팅 🔥

2021-09-28 20:54 UTC, merged