[JDBC 라이브러리 구현하기 - 2단계] 아코(안석환) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #398
Opened 2023-10-03 08:24 UTC by seokhwan-an

안녕하세요! 테오

이번에 리팩토링을 진행하면서 중점을 둔 부분은 다음과 같습니다.
현재 `jdbcTemplate`이 책임지는 부분이 많다고 생각을 해서 그 부분들을 객체 및 인터페이스로 분리하였습니다. 이번에 추가된 것에 대해서 간단하게 설명하겠습니다.
### 구현한 요소
`PrepareStatementGenerator` : connection과 sql을 통해서 prepareStatement를 생성하는 인터페이스입니다.
`PrepareStatementSetter` : prepareStatement의 요소를 설정하는 인터페이스입니다.
`AgrumentPrepareStatementSetter` : `PrepareStatementSetter`의 구현체로 object[]를 가지고 prepareStatement의 요소를 설정합니다. 
`ResultMaker` : prepareStatement를 실행시켜서 결과를 반환해주는 객체입니다.
`SingleResultValidator` : queryForObject의 결과값은 1개이어야 하므로 `ResultMaker`로 부터 생선된 결과값의 개수를 검증하는 유틸 클래스입니다.
### 고민이 되었던 것
현재 `SingleResultValidator`에서 결과값의 개수를 검증할 때 1개가 아닌 모든 상황에서 대해서 예외처리를 하고 있습니다. 결과값이 아예 없는 것(결과값의 수 == 0)인 것도 예외로 처리하면 좋을지 아니면 Optional로 반환을 해주는 것이 좋을지 고민이 됩니다. 현재는 예외로 처리했습니다.

2023-10-03 09:18 UTC, woosung1223 requested changes
안녕하세요 아코 ㅎㅎ
코드가 아주그냥 깔끔하네요 굿입니다.

몇 가지 부분에 대해 코멘트 남겼는데, 정답을 원해서 코멘트를 달았다기보다는 아코의 생각이 궁금해서 단 게 대부분이에요!

티키타카도 언제나 환영이니 부담 갖지 마시고 코멘트 달아주시면 감사하겠습니다!

그리고 질문에 대한 답변인데요,
> 현재 SingleResultValidator에서 결과값의 개수를 검증할 때 1개가 아닌 모든 상황에서 대해서 예외처리를 하고 있습니다. 결과값이 아예 없는 것(결과값의 수 == 0)인 것도 예외로 처리하면 좋을지 아니면 Optional로 반환을 해주는 것이 좋을지 고민이 됩니다. 현재는 예외로 처리했습니다.

사실 저도 이 부분 고민이 조금 되었는데요. 저희가 라이브러리를 구현하는 입장이므로 이를 사용하는 입장에서 생각해보면 좋을 것 같아요.

아코나 제가 JdbcTemplate을 사용해서 DAO를 구현하고 있다고 해볼게요. queryForObject는 어떤 상황에 사용하실 것 같으신가요?

우선 저는 조회 결과의 개수를 예측할 수 없는 상황이라면 리스트 반환타입을 가지는 query를 쓸 것 같아요.

그리고 조회 결과의 개수가 하나일 것이라 예상되는 경우에만 queryForObject를 사용할 것 같아요.

'조회 결과의 개수가 하나일 것으로 예상된다'는 무엇을 의미할까요?

저는 개인적으로 '해당 튜플에 대한 정보를 이미 알고 있다'고 해석할 것 같아요. 그러니까 0개인 경우는 queryForObject 메소드를 사용하는 사용자가 의도한 환경이 아닐 확률이 높은거죠.

이런 맥락에서 보면 queryForObject는 0개일 때 빠르게 예외를 반환하는 편이 더 일반적일 수도 있겠다고 생각합니다.

다만 이건 구현하는 사람 마음인 것 같아서.. 0개일 때 Optional을 반환하게 만들더라도 큰 문제는 없을 것 같다는 생각이 드네요. 

이건 단순히 제 생각이고 아코가 편하신대로 진행해주시면 좋을 것 같아요! 좋은 질문 덕분에 깊게 생각해볼 수 있는 계기가 되었네요 굿 ㅎㅎ

2023-10-03 09:18 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/SingleResultValidator.java
> +        if (resultSize > 1 || resultSize == 0) {
resultSize가 음수가 되는 일은 발생하지 않으니 단순히 `resultSize != 1` 이라고 선언해도 좋을 것 같네요!

2023-10-04 03:15 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>      public <T> List<T> query(final String sql, final RowMapper<T> rowMapper) {
이 부분은 생각하지 못했었네요! 감사합니다 테오

2023-10-04 03:16 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/SingleResultValidator.java
> +        if (resultSize > 1 || resultSize == 0) {
넵 저도 그 방안이 더 좋은 것 같습니다👍👍

2023-10-04 07:46 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/ArgumentsPrepareStatementSetter.java
> +public class ArgumentsPrepareStatementSetter implements PrepareStatementSetter{
현재는 Args로 prepareStatement의 요소를 채워주고 있는데 이는 언제든지 변경이 가능한 부분이라고 생각을 했습니다. 지금은 가변인자로 Object[]로 넘겨주는 방식을 채택했는데 인자를 String으로 ","로 분리를 하는 상황도 있을 것 같다고 생각을 해서 추상화를 진행했는데 이 부분은 약간 상상을 많이 한 부분이기도 합니다. 
고민이 되었던 것이 라이브러리를 개발을 한다고 생각을 하면 언제든지 확장을 가능하게 개발을 해야하는 것인지 아니면 현재 상황에 맞게 처리를 하는 것만큼만 고려를 개발을 해야하는 것인지 고민이 되었습니다.

2023-10-04 08:28 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            SingleResultValidator.validate(results);
제가 먼저 검증 로직을 유틸성 객체로 분리를 했던 이유는 결과물을 검증하는 로직이 점점 많아지는 경우(테오가 이야기 한 것처럼 결과물이 두개인지 검증하는 것)에는 결국 jdbcTemplate에 private 메소들이 많아질 것이라고 생각했기 때문인데요 -> private 메소드가 많아지게 된다면 결국 jdbcTemplate의 책임인가? 라는 고민으로 이어졌습니다. 

고민 끝에 결과의 개수를 검증하는 로직을 분리했습니다.

제가 느낀 객체를 분리하면서 얻는 이점은 다음과 같습니다.
1. 하나의 클래스가 거대해지는 것을 막을 수 있다. -> 즉, 유지보수가 편리해진다.
2. 요구사항 변화에 있어서 확장성이 편리해진다는 것입니다. 

객체 분리를 했을 때 잃게 되는 것은 다음과 같습니다.
1. 잘못 분리를 하게 되면 응집도가 떨어질 수도 있다.
2. 요구사항에 따라 변경이 일어나는 파일의 개수가 많아질 수도 있다.
3. 패키지로 명확하게 분리가 되지 않으면 파일을 관리하는 리소스가 높아진다.

2023-10-04 08:28 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            SingleResultValidator.validate(results);
현재 이름이 `SingleResultValidator`라고 되어 있어서 특정 사항만 검증하는 유틸 클레스로 이해가 되는 것 같습니다. 이 부분을 조금 더 포괄적인 이름인 `ResultValidator`라고 하고 메소드명을 `validateSingleResult`라고 수정을 하겠습니다.

2023-10-04 08:36 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    };
이번에 모든 부분을 추상화를 한다고 생각을 했어서 응집성에 대한 고려를 크게 하지 않고 분리하는 것에만 목적을 두고 했던 것 같습니다, 저도 이 부분에 대해서는 테오가 말해주는 것이 더 좋은 방안이라고 생각합니다. 이 부분에 대해서 수정하겠습니다!

2023-10-04 08:42 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    };
이 부분을 수정할 때 `PrepareStatementManager`라는 객체를 만들어서 prepareStatement를 생성하는 것과 값을 설정하는 것 모두 책임지게 수정을 하였습니다.

2023-10-04 10:47 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>      public <T> List<T> query(final String sql, final RowMapper<T> rowMapper) {
현재 흐름이 query는 list를 반환하고 queryForObject는 하나의 결과물이 나온다는 것 외에는 모두 같은 로직입니다.
그래서 queryForObject 내부에 query를 실행하고 결과물이 하나인지 검증하는 로직으로 중복을 제거했습니다.
혹시 의도하신 부분이 아니면 다시 피드백 부탁드립니다!🙇‍♂️

2023-10-04 11:01 UTC, seokhwan-an commented
안녕하세요! 테오
먼저 꼼꼼한 리뷰 감사합니다! 👍
제가 깊게 생각하지 못했던 부분에  대해서 짚어주어서 제가 왜 객체분리를 하려 했던 것인지 다시 한번 생각해보았습니다!
리뷰 반영한 것과 제 의견을 남겼습니다!

2023-10-04 11:32 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    };
굿 좋아요 ㅎㅎ 이제 PreparedStatementManager의 응집도가 더욱 올라가겠군요! PreparedStatement를 준비하기 위한 모든 과정은 하나의 객체에서 이루어지고 있네요. 설정과 사용이 적절히 분리된 것 처럼 보여요~

기존 JdbcTemplate 구조와는 상관 없이 아코만의 구조를 찾아가셨으면 하는 바램에서 코멘트 남겼는데 잘 하셨네요!

2023-10-04 11:39 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/ArgumentsPrepareStatementSetter.java
> +public class ArgumentsPrepareStatementSetter implements PrepareStatementSetter{
저는 라이브러리를 만드는 입장이라면 추상화에 조금 유의해서 개발을 진행할 것 같아요. 메소드나 인터페이스 등이 한 번 외부로 드러나게 되면 그걸 사용하는 사용자는 반드시 있을거고, 하위호환성을 보장하기 위해서는 변경을 섣불리 할 수 없는 상황에 놓이게 됩니다.

확장을 대비하지 않은 상황에서 -> 확장을 대비하도록 변경되는건 크게 문제라고 생각하지 않습니다. 다만 확장을 대비하도록 해둔 설계에서 다시 축소시키는 일은 생각보다 엄청난 작업일 것 같아요.

만약 정말 확장이 되어야 하는 부분이고, 미래에 100% 일어날 것 같다면 저는 추상화를 선택할 것 같습니다. 

그런데 생각해보니 PrepareStatementSetter의 경우에는 사용자에게 드러날 일이 없으니까, 추상화를 해두어도 문제는 없을 것 같다는 생각도 드네요. 어쨌거나 내부 구현을 바꾸는 일이니까요! 이 부분은 아코에 판단에 맡겨도 될 것 같습니다 ㅎㅎ

2023-10-04 11:43 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            SingleResultValidator.validate(results);
굿 결국 정답은 없고 아코의 근거가 궁금해서 여쭤봤었습니다 ㅎㅎ

Spring이나 기타 라이브러리 구현부를 보다보면 Utils 클래스를 참 많이 사용하더라고요.

이는 객체지향 원칙에 위배되는 내용 아닌가? 싶을 순 있겠지만, 아코가 말씀해주신대로 얻는 것도 많으니 타당하다고 생각합니다.

이전에 리뷰어님께 들은 내용인데, 실무에서는 비즈니스 검증 로직을 하나의 클래스에 모아두는 경우도 있다고 하더라고요. (유지보수의 편의성 때문에)

아무튼 더욱 좋은 코드로 변한 것 같습니다! 👍 고생하셨어요~

2023-10-04 11:44 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>      public <T> List<T> query(final String sql, final RowMapper<T> rowMapper) {
정확히 제가 의도한 방향으로 작성해주신 것 같습니다 💯 굿굿

2023-10-04 11:50 UTC, woosung1223 approved these changes
안녕하세요 아코~
빠르게 반영해주셨네요 좋습니다!

논의를 통해 확실히 더 좋은 코드로 바뀐 것 같아요!

코멘트를 통해 얼마나 아코가 평소에 깊게 생각하고 있는지도 알 수 있었어요.

고생하셨습니다~ 3단계로 가시죠! 💯

2023-10-04 11:50 UTC, woosung1223 commented on jdbc/src/main/java/org/springframework/jdbc/core/preparestatement/PrepareStatementGenerator.java
> +}
제가 못 찾는 것일수도 있겠지만, PreparedStatementGenerator가 사용되는 부분이 없는 것 같네요. 

해당 역할을 PreparedStatementManager가 수행하고 있으니 제거해도 좋을 것 같아요~

2023-10-04 11:51 UTC, merged

2023-10-06 12:42 UTC, seokhwan-an commented on jdbc/src/main/java/org/springframework/jdbc/core/preparestatement/PrepareStatementGenerator.java
> +}
이 부분 실수로 제거를 못했습니다. 감사합니다!☺️