[JDBC 라이브러리 구현하기 - 1, 2단계] 파피(김태완) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #43
Opened 2021-09-27 10:44 UTC by TaewanKimmmm

안녕하세요 조앤~ 이번 미션은 코드를 간결하고 보기 좋게 줄이는 과정에서 많이 배울 수 있었던 것 같아요!!

시간 내어 리뷰해주셔서 감사합니다 ㅎㅎ🙏🙏 조앤의 거침없는 피드백 부탁드립니다!!!!!!!

2021-09-29 01:32 UTC, seovalue commented on README.md
> +# 1단계 - JDBC 라이브러리 구현하기
2단계도 함께 수행하신거죵 ?!?!?

2021-09-29 01:32 UTC, seovalue commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(UserDao.class);
Logger가 활용되지 않고 있는 것 같아요 !!

2021-09-29 01:33 UTC, seovalue commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +    }
delete 관련 메서드도 하나 추가해보시면 좋을 것 같아요! :)

2021-09-29 01:34 UTC, seovalue commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.query(sql, (ResultSet resultSet) ->
반복되는 ResultSet은 static하게 추출해서 사용해보시는 건 어떨까요? ㅎㅎ

2021-09-29 01:38 UTC, seovalue commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +public class UserDao {
궁금한 점이 있어요. 
- app패키지를 통해 개발자가 구현하도록 하는 것이 아닌, jdbc 라이브러리가 도메인인 User와 Dao인 UserDao를 갖고 있도록 구성한 이유가 궁금해요!
- UserDaoTest는 app 패키지에, UserDao는 jdbc 패키지에 존재하는 이유가 있나요?

2021-09-29 01:39 UTC, seovalue commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +    public User findByAccount(String account) {
![Screen Shot 2021-09-29 at 10 38 51 AM](https://user-images.githubusercontent.com/48412963/135188475-ef2152d1-6dbd-4ef2-8dac-180a741a0fa5.png)
테스트가 통과하지 않아요 ㅠㅠ

2021-09-29 01:41 UTC, seovalue commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(JdbcTemplate.class);
파피가 만든 JdbcTemplate 잘 보았어요! 한가지 아쉬운 점은, 파피가 만드신 JdbcTemplate이 잘 동작하는 지 확인하고 싶은데, 테스트할 방법이 없는 점이 아쉬운 것 같아요.
JdbcTemplateTest도 구현해주시면 다른 개발자가 파피가 만든 라이브러리를 믿고 사용할 수 있을 것 같아요 ><

2021-09-29 01:42 UTC, seovalue commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private void setValues(PreparedStatement preparedStatement, Object[] values) throws SQLException {
강의 자료 2단계 리팩토링을 혹시 보셨는지 모르겠지만,
PreparedStatementSetter로 분리하였을 때와 분리하지 않았을 때 어떤 차이점을 갖고, 어떤 장단점을 가질까요?

2021-09-29 01:43 UTC, seovalue commented on jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +@FunctionalInterface
FunctionalInterface 어노테이션을 달아주신 이유가 무엇인가요?
없으면 함수형 인터페이스로 동작하지 않나요? ><

2021-09-29 01:45 UTC, seovalue requested changes
안녕하세요, 뽜쀠! 조앤입니당 ㅎ_ㅎ
후,, 일어나자마자 뽜쀠 리뷰를 바삐 했네요 ~  ​( ͡° ͜ʖ ͡°) 

구현해주신 코드 잘 보았어요, 재밌게 구현해주셨다고 했는데 깔끔하게 잘 구현해주신 것 같아요 ><
하지만 테스트가 조금 더 추가되면 좋을 것 같고, 도메인 및 dao 패키지 관련해서 한번 고민해보시면 좋을 것 같아서 리뷰 남겼어요! 확인해주시고, 리뷰 재요청 부탁드릴게요 🚀

오늘도 좋은 하루 보내길 바라요 🎶

2021-09-30 01:41 UTC, TaewanKimmmm commented on README.md
> +# 1단계 - JDBC 라이브러리 구현하기
네!!!!!!!!!!!!!!!!!

2021-09-30 01:51 UTC, TaewanKimmmm commented on jdbc/src/main/java/nextstep/jdbc/RowMapper.java
> +@FunctionalInterface
동작하지 않는 건 아니지만 @FunctionalInterface 어노테이션을 붙일 경우 컴파일러 차원에서 단일 추상 메서드를 갖춘 인터페이스인지 검사해준다고 해서 붙였습니다 ><

2021-09-30 01:56 UTC, TaewanKimmmm commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    private void setValues(PreparedStatement preparedStatement, Object[] values) throws SQLException {
PreparedStatementSetter 대신 가변 인자를 사용하도록 변경했는데요!

- 매번 구현하여 사용해야 하는 점
- 특히 findAll 메서드같은 경우 PreparedStatementSetter가 필요없는데 인자로 받고 있으므로 null을 이용해야 했던 점

을 개선할 수 있었어요!

2021-09-30 01:59 UTC, TaewanKimmmm commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(UserDao.class);
JdbcTemplate에서만 남기도록 하였습니다 ㅎ ㅎ

2021-09-30 02:34 UTC, TaewanKimmmm commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +        return jdbcTemplate.query(sql, (ResultSet resultSet) ->
아주 좋은 아이디어입니다!

2021-09-30 07:32 UTC, TaewanKimmmm commented on jdbc/src/main/java/com/techcourse/dao/UserDao.java
> +public class UserDao {
띠용? 왜 이렇게 돼있지!!! 다시 고쳤습니다~

2021-09-30 14:23 UTC, seovalue commented on README.md
> +# 2단계 - 리팩터링
👍

2021-09-30 14:23 UTC, seovalue commented on app/src/main/java/com/techcourse/config/DataSourceConfig.java
> +        jdbcDataSource.setUrl("jdbc:h2:tcp://localhost/~/mem:test;DB_CLOSE_DELAY=-1;");
이렇게 바꿔주신 이유가 있으신가요?!?

2021-09-30 14:26 UTC, seovalue commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +	private static final RowMapper<User> ROW_MAPPER = (resultSet) -> {
RowMapper의 mapRow 파라미터로 resultSet, rowNum을 두어서 우리가 jdbcTemplate을 사용할 때 처럼 구현해봐도 재밌을 것 같아요 ㅎㅎ
```java
private static final RowMapper<User> rowMapper = (rs, rowNum) ->
        new User(
            rs.getLong(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4)
        );
```

2021-09-30 14:31 UTC, seovalue commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +	private static final JdbcDataSource JDBC_DATA_SOURCE = new JdbcDataSource();
요런것도 있군요???????

2021-09-30 14:33 UTC, seovalue commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +		String schemaSql = "create table if not exists users (\n"
userDaoTest에서는 어떻게 resources/schema.sql을 읽어오는게 가능할까요??

2021-09-30 14:37 UTC, seovalue approved these changes
Hello fafi I'm Joanne

수정해주신 것 확인했습니다!!!! 테스트도 생기고, 코드의 가독성도 좋아진 것 같아요!! 👍 👍 
jdbc 라이브러리 구현 미션인지라, 저도 미션할 때 controller의 inMemoryRepository를 userDao로 변경하는 작업은 따로 수행하지 않았었는데요, 시간 되실 때 한번 해보셔도 좋을 것 같다는 생각이 드네요! >< 추가적으로 몇가지 궁금코멘트 남겼는데요!! 현 코드도 요구사항은 모두 만족하기에 우선은 어프루브하구 머지할게요 ㅎㅎ 
미션 하시느라 고생 많으셨어요 ~!~! 소주나 한병 합시다. 항상 화이팅 하십쇼!!! ^^7

2021-09-30 14:37 UTC, merged