[JDBC 라이브러리 구현하기 - 2단계] 오은비(주디) 미션 제출합니다
woowacourse/jwp-dashboard-jdbc pull request #434
Opened 2023-10-04 16:11 UTC by eunbii0213

안녕하세요 성하!! 추석연휴 잘 보내셨을까요? 늦어서 죄송합니다.. 
이번 미션도 잘 부탁드립니다 🙇‍♂️

2023-10-05 00:13 UTC, sh111-coder requested changes
안녕하세요 주디! 성하입니다!!
부분 부분 리팩토링해주시고 테스트도 작성해주셨네요! 👍🏻👍🏻

다만, 1단계에서 코멘트 남겼었던 부분들이 수정이 안된 부분이 있어서 RC 하겠습니다!
수정 후 다시 리뷰 요청 주세요! 🙇🏻‍♂️

2023-10-05 00:13 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            throw new DataAccessException("too many result. expected 1 but was " + results.size());
Result의 Size에 대한 예외는 `DataAccessException`보다는 
Size에 대한 커스텀 예외를 만드는 게 더 좋을 것 같아요!
DataAccess는 성공하는데 Result Size 때문에 예외가 발생하는 거니까요!

2023-10-05 00:13 UTC, sh111-coder commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
>  class JdbcTemplateTest {
와 JdbcTemplate 테스트까지 하셨군요!! 

테스트 하신 김에 어제 강의에서 메모리 H2를 사용해서 update, query 테스트를 진행할 수 있더라고요!
시간이 남으신다면 해당 기능도 테스트하면 좋을 것 같습니다!! 👍🏻👍🏻👍🏻

2023-10-05 00:13 UTC, sh111-coder commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +                resultSet.getString("email")));
이 부분 1단계 코멘트에서 수정 제안 드렸었는데 반영이 안된 것 같아서 다시 제안 드립니다!!
따로 이유가 있어서 안 하신거라면 코멘트로 남겨주시면 좋을 것 같아요!
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/338#discussion_r1341915817

2023-10-05 00:13 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>          List<T> results = query(sql, rowMapper, params);
이 부분 1단계 코멘트에서 수정 제안 드렸었는데 반영이 안된 것 같아서 다시 제안 드립니다!!
따로 이유가 있어서 안 하신거라면 코멘트로 남겨주시면 좋을 것 같아요!
https://github.com/woowacourse/jwp-dashboard-jdbc/pull/338#discussion_r1341915726

2023-10-06 02:22 UTC, eunbii0213 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +                resultSet.getString("email")));
헉스 제가 반영을 깜빡했군요..!! 바로 하겠습니다!

2023-10-06 02:22 UTC, eunbii0213 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
>          List<T> results = query(sql, rowMapper, params);
아이구 죄송해요 성하 ㅜㅜ 바로 하겠습니다!

2023-10-06 02:34 UTC, sh111-coder approved these changes
수정 제안 드린 부분 반영 잘 해주셔서 Approve & Merge 할게요!!
다음 단계도 화이팅해봐욥! 👍🏻👍🏻👍🏻

2023-10-06 02:35 UTC, merged