[JDBC 라이브러리 구현하기 - 1, 2단계] 조이(김주원) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #45
Opened 2021-09-27 14:51 UTC by Joyykim

안녕하세요 찰리!!!!😀😀😀
다른 일이 많아 미션 제출이 늦어졌네요ㅜ

jdbcTemplateTest를 아직 다 작성 못했네요. 내일 작성해서 올릴게요!

그리고 궁금한게 있는데, `ContextLoaderListener`가 왜 저는 동작을 안하는걸까요???
제 리뷰이인 루트의 코드에서는 `contextInitialized()`가 잘 먹히던데;;

2021-09-28 00:16 UTC, Gomding requested changes
안녕하세요 조이 🙇 
바쁜 스케쥴사이에 미션 구현하느라 고생하셨어요!!

README.md에 1단계만 적혀있어서 우선 1단계만 생각하고 리뷰를 진행했습니다 😃 

몇가지 코멘트 남겼으니 확인하시고 조이의 많은 의견 부탁드립니다!!
궁금하거나 이해가 안되는 코멘트가 있으면 언제든 DM 주세요 :)

2021-09-28 00:16 UTC, Gomding commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
ResultSet 의 fetchSize는 원하시는 값이 아닌것 같아요!
현재 로그인하면 무조건 여기서 예외가 터지면서 로그인이 안되고 있네요 😞 

[영어라서 조금 울렁거릴 수 있는 oracle의 JDBC ResultSet 문서](https://docs.oracle.com/cd/E11882_01/java.112/e16548/resltset.htm#JJDBC28621)
여기서 fetchSize 쪽을 참고해주세요 😉

2021-09-28 00:16 UTC, Gomding commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
원래 조이의 의도대로 resultSet의 size가 1이 아닌지 위에서 검사를 했다면
rs.next로 한번 더 검증을 거친 이유가 있을까요?

2021-09-28 00:16 UTC, Gomding commented on mvc/src/main/java/nextstep/mvc/DispatcherServlet.java
> +            if (handler.isEmpty()) {
조이의 매의눈에 무릎을 탁 치고갑니다 😮 😮 😮 😮

2021-09-29 05:04 UTC, Joyykim commented on app/src/main/java/com/techcourse/JwpApplication.java
> +        final Context context = tomcat.addWebapp("", docBase);
<img width="1470" alt="스크린샷 2021-09-29 오후 1 59 56" src="https://user-images.githubusercontent.com/56679885/135206001-fcbafedb-c9db-4a6b-b22a-87db34ea6029.png">

어플리케이션을 구동하니 위와 같은 warning이 떠서 수정했어요.
`context path는 empty string이거나, '/'로 시작하면서 '/'로 끝나지 않아야 한다.`

옆에가 짤려서 전체 텍스트도 보여드릴게요!
```
9월 29, 2021 1:58:28 오후 org.apache.catalina.core.StandardContext setPath
경고: A context path must either be an empty string or start with a '/' and do not end with a '/'. The path [/] does not meet these criteria and has been changed to []
```

2021-09-29 05:06 UTC, Joyykim commented on app/src/main/java/com/techcourse/config/DataSourceConfig.java
>      public static javax.sql.DataSource getInstance() {
앗ㅋㅋ 수정하겠습니다!

2021-09-29 05:09 UTC, Joyykim commented on app/src/main/java/com/techcourse/controller/UserController.java
> +        }
userDao에서 jdbcException을 처리하고 상위로 Optional을 반환하면 확실히 계층의 역할이 분명해지겠네요!

2021-09-29 05:24 UTC, Joyykim commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
UserDao에서 DataSource를 초기화하는건 두 클래스가 너무 결합된다고 생각해서 처음엔 저렇게 했어요.
근데 지금보니 그것때문에 중복코드가 많이 발생하네요.
부생성자를 만들어서 (1) 외부에서 DataSource를 결정할수도있고, (2) DataSource가 없다면 디폴트로 `DataSourceConfig.getInstance()`를 사용하도록 변경하겠습니다~

2021-09-29 05:24 UTC, Joyykim commented on app/src/main/java/com/techcourse/support/jdbc/init/DatabasePopulatorUtils.java
> +                 Statement statement = connection.createStatement()) {
맛있게 리팩토링했습니다ㅎㅎ

2021-09-29 05:24 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        logSql(sql);
아이고 이 부분은 놓쳤네요

2021-09-29 06:19 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
그렇네요! fetch size 수정하면서 같이 고치겠슴돠~~~~

2021-09-29 06:25 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
fetchSize는 드라이버가 database cursor로 부터 한번에 조회해오는 row의 개수군요!

로그인시 발생하는 에러도 확인했어요. 근데 그 에러는 fetchSize와는 다른 문제네요ㅠㅠ
왜인지는 모르겠지만 UserController에서 `userDao.findByAccount`를 실행하려 할 때 `JdbcTemplate.queryOne()`메서드를 찾을 수 없다고 하네요...ㅠㅠㅠㅠ

`Caused by: java.lang.NoSuchMethodError: 'java.lang.Object nextstep.jdbc.JdbcTemplate.queryOne(java.lang.String, nextstep.jdbc.RowMapper)'`

2021-09-29 06:32 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
`queryOne(java.lang.String, nextstep.jdbc.RowMapper)`이건 리팩토링 전의 파라미터 타입인데 이걸 왜 찾는걸까요?....ㅠㅠ

2021-09-29 08:07 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
재클론으로 해결했슴다...!

2021-09-29 08:51 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            throw new RuntimeException(e);
수정했습니다!!

2021-09-30 09:22 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        };
"구현체 대신 콜백"이란 말을 제대로 이해 못했어요. 혹시 콜백 람다객체를 콜백이라고 표현하신건가요? 그럼 구현체는 뭐죠..?

2021-09-30 09:22 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        };
"구현체 대신 콜백"이란 말을 제대로 이해 못했어요. 혹시 콜백 람다객체를 콜백이라고 표현하신건가요? 그럼 구현체는 뭐죠..?

2021-10-13 00:39 UTC, Gomding commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public int update(String sql, Object... args) {
저도 구구한테 받았던 피드백인데 update 라는 메서드는 insert, update, delete 의 기능으로 주로 사용하는데
update 라는 이름만으로 메서드를 제공하면 사용자 입장에서는 헷갈릴 수 있는 포인트가 될 수 있다고 생각해요
그래서 다양한 이름의 메서드로 제공하는건 어떻게 생각하시나요?

ex) insert(), update(), delete()

2021-10-13 00:41 UTC, Gomding commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    void update() throws SQLException {
테스트 잘 작성해주셨어요! 
요 테스트에만 @DisplayName을 깜빡하신것 같네요 😄

2021-10-13 00:51 UTC, merged

2021-10-13 03:42 UTC, Joyykim commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    public int update(String sql, Object... args) {
오 그렇겠네요! 기존 jdbcTemplate의 기능만 생각하고 있었던것 같아요.