[JDBC 라이브러리 구현하기 - 3단계] 아마란스(송세연) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #475
Opened 2023-10-06 13:23 UTC by amaran-th

안녕하세요 폴로!
저번 단계에서는 제가 코멘트 하나를 미처 못보고 지나쳤더라구요...🥲
그 때 주신 코멘트 덕에 어떻게 하면 unchecked exception 처리를 깔끔하게 할 수 있을지 오래 고민할 수 있었어요!
처음엔 함수형 인터페이스&람다식을 통해 try-catch와 내부 로직을 분리했는데요,
sql exception이 처리되지 않았다는 컴파일 에러가 발생해서 의아했었는데 함수형 인터페이스를 직접 정의하고 메서드 시그니처에 exception을 던지도록 하면 해결된다는 걸 처음 알게 되었어요. 감사합니다ㅎㅎ

남은 미션에서는 코멘트를 놓치는 일이 없도록 하겠습니다...!
그럼 3단계도 잘 부탁드립니다~~!

2023-10-07 07:47 UTC, green-kong requested changes
안녕하세요 아마란스!
4단계도 잘 부탁드리겠습니다! ㅎㅎ

조금더 리팩토링 해볼수 있는 지점들과,
깜빡하고 놓치신것 같으 부분들,
조금 더 개선해보면 좋을 것들에 대해 코멘트 남겨놨습니다!

2023-10-07 07:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +    }
음.. 제가 잘 설명할 자신이 없긴한데... 노력해볼게요..

아마란스도 미션과 프로젝트를 하시면서 느꼈겠지만, 종종 서비스가 서비스를 의존하는 경우도 참 많이 발생하죠.
Aservice#doA에서 Bservice#doB 를 호출 한다고 가정해볼게요.

```java
public class Aservice {
    public void doA() {
        // doA 로직
        bService.doB();
    }
}
```

이런 식으로 말이죠.
만약 doA와 doB가 같은 트랜잭션으로 묶여야 된다고 생각을 해볼까요?
현재 아마란스 코드의 구조라면

```java
public class Aservice {
    public void doA() {
        transactionManager.executeInTransaction((conn)->{
        
            // doA 로직
            bService.doB(conn);
        });
    }
}
```

이런식으로 변경이 되어야 겠네요.

2023-10-07 07:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +    }
흠 그런데 여기서 한가지 가능성을 추가해 볼게요.

doB는 항상 doA에서만 호출 되는게 아니라, 다른 요청에서는 doB의 작업만 하는 경우도 있어요.
그리고 doB의 작업 역시 하나의 트랜잭션을 묶여야 하죠.

```java
public class Bservice {
    public void doB() {
        transactionManager.executeInTransaction((conn)->{
            //do B 로직
        });
    }
}
```

그런데 doA에서 호출되는 경우에는 doA와 하나의 트랜잭션으로 묶이기 위해 connection을 param으로 넘겨 받았는데,
여기선 그럴수가 없게 되버렸네요.

그럼 doB를 overload 해야할까요?
흠 한번 고민을 해보시면 좋을것 같네요.

트랜잭션이 생성되는 종료되는 단위에 대해 생각해보시면 도움이 되지 않을까 싶습니다!

2023-10-07 07:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    }
앗 업데이트를 오버로딩 하셨네요?
- queryForObject`와 `query` 도 모두 오버로딩 하실건가요?
  - 오버로딩 없이 할수 있는 방법은 없을까요?

- 아니면 트랜잭션은 쓰기작업만 묶이면 된다고 판단하신 건가요?
  - 만약 쓰기-읽기-쓰기 순으로 작업이 진행되야 하는 트랜잭션이 있다면, 하나의 작업인데 생성되는 Connection은 2개이겠네요?

2023-10-07 07:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            return executor.execute(rs);
음. 이렇게 만들면 update에는 적용할 수가 없겠네요.
모든 메서드에 범용적으로 사용될 수 있게 만들수는 없을까요?

2023-10-07 07:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +        }
예외가 터지면 롤백을 해줘야 되지 않을까요?

2023-10-07 11:58 UTC, amaran-th commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +        }
commit()을 해주지 않은 채로 connection이 close되면 rollback()을 호출해준 것과 동일한 효과를 보이는 것 같더라구요. 실제로 UserServiceTest에 정의된 테스트도 통과하는 것을 확인했습니다!
명시적으로 rollback()을 호출해주는 것도 좋겠지만, 개인적으로 conn.rollback()을 수행하기 위해 한 번 더 try-catch문으로 감싸야 하는 것이 마음에 들지 않아서 이렇게 구현했습니다ㅎㅎ

2023-10-08 06:03 UTC, green-kong commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +        }
> 개인적으로 conn.rollback()을 수행하기 위해 한 번 더 try-catch문으로 감싸야 하는 것이 마음에 들지 않아서 이렇게 구현했습니다ㅎㅎ

궁금해서 여쭤 보는건데 그럼 connection.rollback() 하다가 예외 터지는건 어디서 catch가 되는 건가요?

2023-10-08 06:39 UTC, amaran-th commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +    }
처음엔 말씀하신 후자의 내용대로 판단한 것이 맞습니다...!
그런데 말씀을 듣고보니, 그렇네요...제가 간과하고 있었나봅니다.
음...오버로딩 없이 구현한다는 걸 Jdbc 템플릿의 메서드들이 Connection 객체를 파라미터로 받지 않게 해야 한다는 것으로 이해했는데, 맞을까요?

Connection 파라미터를 어떻게 하면 없앨 수 있을까 고민을 해봤는데, Connection객체를 static하게 관리하면 될 것 같더라구요...!
그래서 미션 4단계를 참고해서 TransactionSynchronizationManager를 구현해서 해결해보았습니다!

2023-10-08 07:12 UTC, amaran-th commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +    }
오...이렇게 실제 있을 법한 상황까지 가정해서 코멘트를 남겨주시니 왠지 감동이네요!
감사합니다ㅎㅎ
제가 이해한 대로라면 executeInTransaction() 메서드가 Consumer<Connection>을 인자로 받기 때문에 서비스 간 의존 관계에서 활용하기 어렵다는 것이 맞을까요?
밑의 [다른 코멘트](https://github.com/woowacourse/jwp-dashboard-jdbc/pull/475#discussion_r1349480868)를 먼저 반영하면서 connection 파라미터를 제거해주었는데, 그러면서 이 문제도 함께 해결이 된 것 같습니다!

2023-10-08 08:16 UTC, amaran-th commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +            return executor.execute(rs);
코멘트 반영하여 update에서도 try-catch문을 분리할 수 있도록 구현하였습니다!

2023-10-08 08:26 UTC, amaran-th commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +        }
음 저는 connection을 close()할 때 실제로 rollback()이 호출되는 것이 아니라, transaction을 시작한 후 발생한 변경사항은 결국 commit()을 호출해야 실제 DB에 반영이 되는데, commit()을 하지 않고 연결을 끊어줌으로서 실제로 rollback된 것과 동일한 결과가 나오는 것으로 이해해했습니다!

2023-10-09 05:33 UTC, green-kong commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionManager.java
> +        }
음 그렇군요 덕분에 하나 배워갑니다!
동작은 정상적으로 하지만.. 제 성격때문인지 좀 찜찜하긴하네요 ㅎㅎ
현재 미션에서는 괜찮지만 다른 상황에서 생길 사이드이펙트가 있지 않을까 하는 염려가 들긴합니다ㅎㅎ

2023-10-09 05:47 UTC, green-kong approved these changes
안녕하세요 아마란스!
리뷰반영 잘해주셔서 감사합니다!

한가지 놓치신 부분이 있는것 같아 코멘트 남겨두었어요!
3단계는 머지 할테니 4단계 진행하시며 함께 생각해보시죠!

4단계에서 만나요~

2023-10-09 05:47 UTC, green-kong commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        try (final PreparedStatement pstmt = getPreparedStatement(sql, obj, conn)) {
`TransactionManager` 를 통해 DB와 통신하는 경우에는 `TransactionManager` 에서 connection 이 close() 되지만,
그렇지 않은경우 (예를 들어 UserService#findById 또는 insert) 같은 경우는 close가 안될것 같네요.

꼭 트랜잭션을 걸어줘야만 connection이 close 되는게 맞을까요???

2023-10-09 05:47 UTC, merged