[JDBC 라이브러리 구현하기 - 3단계] 로지(윤가영) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #487
Opened 2023-10-07 08:28 UTC by kyY00n

가비 하이 ☀️
가비를 쫓아 3단계를 구현해 왔습니다!
일단은 리팩토링을 진행하진 않고 먼저 구현했습니다.
다른 크루들의 구현 방법을 보니 트랜잭션 경계를 만들어주는 역할을 분리했더라구요!
저는 조금 더 공부해보고 4단계 때 적용해보도록 하겠습니다.

tdd로 진행하지 않아서 기능이 구현되었지만 테스트가 없는 것들이 있습니다. (특히 connection 객체를 인자로 받는 메서드)
이것들은 리팩토링 과정에서 없애려고 계획중입니다..! 도중에 리뷰를 받는 것 같아 죄송한데요. 이런 경우에도 테스트코드를 꼭 짜는게 맞을까? 라는 질문을 스스로 하게 되었고 제 결론은 No 였습니다. 기존의 테스트 코드를 만족하는 수준에서 다음 단계를 넘어가려고 합니다. 가비의 생각이 다르다면 request change 해주셔도 괜찮으니 의견주세요 :D

2023-10-07 12:42 UTC, iamjooon2 requested changes
안녕하세요 로지
평안하시죠?

저 역시 LMS에 충실하게 깡구현했답니다 (4단계에서 리팩터링 하라는 구구의 뜻이라 생각하며... )
테스트에 대해서 로지가 내린 결론 역시 공감합니다...만 (제가 그랬거든요...)

짚고 ~~집사의고민아님~~ 넘어가야할 것이 있는 것 같아 RC로 남깁니다
남긴 코멘트 확인해주고 답 남겨주시면 감사하겠습니다

2023-10-07 12:42 UTC, iamjooon2 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +                        () -> userService.changePassword(1L, newPassword, createBy)),
이친구 옮겨주신 이유가 궁금합니다!

2023-10-07 12:42 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +
감사합니다 👍

2023-10-07 12:42 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
UserDao에서 Connection을 인자로 받도록 구현하셨군요

다만 받아온 connection을 사용하고 있지는 않습니다
덕분에 userDao와 userHistoryDao가 다른 connection을 사용하게 됐네요...!

2023-10-07 12:42 UTC, iamjooon2 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
>  @Disabled
> UserServiceTest 클래스에서 @Disabled를 삭제하고 미션을 진행한다.

다음 리뷰요청때는 지우고 보내주세요

2023-10-08 05:29 UTC, kyY00n commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +                        () -> userService.changePassword(1L, newPassword, createBy)),
저는 assertThrows 도 단언문이고 얘가 실패하면 테스트도 통과하지 않기 때문에 assertAll에 넣었어요. 만약 given 에서 예외를 던지는 것을 명시하기 위해서라면, 이 단언문을 없애버렸을 거예요. (만약 명시를 하고 싶다면 mockito bdd 스타일을 이용했을 것 같습니다.)

2023-10-08 05:39 UTC, kyY00n commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
> +        System.out.println("에에에에에????");
제가 너무 정신이 없었네요ㅜㅜ..

2023-10-08 05:39 UTC, kyY00n commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +
소듕한 리뷰니까.

2023-10-08 05:40 UTC, kyY00n commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
>  @Disabled
감사합니당 ✅

2023-10-08 05:49 UTC, kyY00n commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +    }
제가... 테스트를 이상하게 짰었어요. 고쳤습니다!! ㅜㅜ 죄송해요 가비.. 알려주셔서 감사합니다

2023-10-08 06:35 UTC, iamjooon2 approved these changes
답변 하나하나 달아주셔서 감사합니다 로지
함께 4단계 하러 가시죠🚀

2023-10-08 06:35 UTC, iamjooon2 commented on app/src/main/java/com/techcourse/service/UserService.java
> +            final var user = findById(connection, id);
옹... 전 읽기 요청은 connection 안넣어줬는데 꼼꼼하십니다

2023-10-08 06:35 UTC, iamjooon2 commented on app/src/test/java/com/techcourse/service/UserServiceTest.java
> +                        () -> userService.changePassword(1L, newPassword, createBy)),
설명과 함께 명시적으로 bdd 적용해주시는 센스까지...!

덕분에 바로 로지의 의도가 바로 이해됐습니다 감사합니다!

2023-10-08 06:36 UTC, merged