[JDBC 라이브러리 구현하기 - 4단계] 성하(김성훈) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #489
Opened 2023-10-07 08:40 UTC by sh111-coder

안녕하세요 루쿠! 빠르게 리뷰해주셔서 4단계 구현할 수 있었어요!! 👍🏻👍🏻

이번에는 미션 요구사항에 나온대로 구현을 진행해봤어요!
1. Connection을 파라미터로 받는 서비스의 로직들을 제거하고, `DataSourceUtil` & `TransactionSynchronizationManager`을 사용하여 Connection 동기화
2. 트랜잭션 서비스 추상화 
  * `UserService` -> Impl : `AppUserService` / `TxUserService`
  * `TxUserService`에서 트랜잭션 처리 로직 중복 -> `TransactionExecutor`을 사용하여 Service 로직을 함수형 인터페이스로 받아서 처리
    * Return Type 존재 여부에 따라서 `execute` 메소드 오버로딩해서 함수형 인터페이스를 다르게 받아서 처리

2023-10-08 14:09 UTC, aiaiaiai1 requested changes
안녕하세요 성하~ 
4단계 빠르게 구현해주셨네요!
몇가지 의견과 코멘트 남겨드렸는데 확인부탁드려요~

2023-10-09 05:04 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return connectionMap.get(key);
확실히 그렇네요!! 수정했습니다!!

2023-10-09 05:36 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
>      }
> bind 할때마다 새로운 map을 만들어서 resources에 set 해주면은 기존에 resources에 존재했던 DataSource에 대한 Connection의 map 정보가 사라지게 될거같아요!

해당 부분은 수정했습니다!!

> 그리고 if문을 통해 mappedConnection 의 값이 존재하면 예외를 터트리고 있는데
bind 할 Connection은 매번 값이 존재해서 예외가 무조건 발생하게 되지 않나요?! 성하의 의도가 궁금합니다!

이 부분은 `Connection mappedConnection = connectionMap.put(key, value);`에서 Map의 put의 값을 받고 있는데요!
Map에서 put 메소드의 리턴 값의 의미는 다음과 같습니다!

> the previous value associated with key, or null if there was no mapping for key. (A null return can also indicate that the map previously associated null with key, if the implementation supports null values.)

요약하면, 이전에 맵에 key에 해당하는 값이 존재한다면 해당 값을 반환하고, 존재하지 않았다면 null을 반환합니다!
따라서 `mappedConnection`이 null이 아니라면 이미 스레드에 리소스가 bind 되어 있다는 것을 의미하므로 
예외를 던져주게 구현했습니다!! 

그래서 put을 하기 전에 이미 존재하는 Connection이 존재한다면 예외를 발생시키도록 했습니다!

2023-10-09 05:48 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
>  }
넵!!! 그렇네요 ㅠㅠ
수정했습니다!!

2023-10-09 06:10 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
> +            TransactionSynchronizationManager.unbindResource(dataSource);
아!! 순서 변경하는게 좋은 것 같아요!!! 수정했습니당! 👍🏻👍🏻

2023-10-09 06:28 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
> +    }
중복이 발생하긴 하지만, null을 넘겨주는 것 보다는 오버로딩이 개인적으로 더 좋은 것 같아서 이대로 놔두려고 하는데 괜찮을까요?!

2023-10-09 06:35 UTC, sh111-coder commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
좋은 것 같아요!! 수정했습니다! 👍🏻👍🏻

2023-10-09 06:35 UTC, sh111-coder commented
리뷰 감사합니다 루쿠!! 좀 급하게 4단계 작성해서 `TransactionSynchronizationManager` 구현 부분에
허점이 좀 많았던 것 같아요!!
남겨주신 코멘트 기반으로 리팩토링 진행했습니다!!

2023-10-10 04:45 UTC, aiaiaiai1 commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
>      }
아하 그렇군요! 알려주셔서 감사합니다~

2023-10-10 04:45 UTC, aiaiaiai1 commented on jdbc/src/main/java/org/springframework/transaction/TransactionExecutor.java
> +    }
넵 좋습니다 👍

2023-10-10 04:58 UTC, aiaiaiai1 requested changes
안녕하세요 성하! 피드백 반영해주신거 확인했어요!
다만 한가지 걸리는 부분이 있는거 같아서 RC 보내봅니다..!
다음 요청때 바로 머지하도록 할께요~

2023-10-10 04:58 UTC, aiaiaiai1 commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
>          }
현재 connectinMap에서 값을 넣고 올바르지 않으면 예외를 터트려주고있지만 잘못된 값은 map에 들어가게 되는 같아요
그래서 값을 넣기전에 먼저 검증을해주는건 어떨까요??

2023-10-10 05:39 UTC, sh111-coder commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
>          }
해당 부분은 `넣은 값이 올바르지 않으면 예외를 터트려주는 것`이 아니라 
`넣은 값이 이미 존재한다면 예외를 터트려주는 것`으로 이해하시면 될 것 같아요!

`Connection mappedConnection = connectionMap.put(key, value);`에서 나오면
mappedConnection은 해당 key에 해당하는 value가 존재한다면 존재하는 value를 반환하고, 
key에 해당하는 value가 없다면 Map에 key, value를 넣고 null이 들어가게 됩니다!

그래서 예외를 발생시키는 이유가, 이미 ConnectionMap에 DataSource에 해당하는 Connection이 존재한다면
이미 스레드에 bind된 Resource가 있는 것이므로 예외를 발생시켰습니다!

그래서 결론적으로 put을 한 결과가 if 검증에서 필요해서 순서는 저대로 해야하는 것 같아요!

2023-10-11 01:37 UTC, aiaiaiai1 approved these changes
안녕하세요 성하!
피드백 반영하시느라 고생하셨어요 ㅎㅎ
미션 여기서 마무리할께요! 다음 미션도 화이팅입니다~ 🚀

2023-10-11 01:37 UTC, merged