[JDBC 라이브러리 구현하기 - 3단계] 주디(오은비) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #508
Opened 2023-10-08 03:08 UTC by eunbii0213

안냐새여 성하~ 방가버~ㅎㅎ 즐거운 주말입니다~~
리뷰 부탁해오~~

2023-10-08 04:08 UTC, sh111-coder requested changes
안녕하세요 주디~~~
3단계 요구사항인 트랜잭션 적용을 잘 해주신 것 같아요!

다만 한 가지 궁금한 부분이 생겨서 코멘트 답변해주시면 
바로 Approve & Merge 하도록 하겠습니다!!

2023-10-08 04:08 UTC, sh111-coder commented on app/src/main/java/com/techcourse/service/UserService.java
> +    public void changePassword(final long id, final String newPassword, final String createBy) throws SQLException {
여기서 SQLException을 처리하지 않고, throws한 이유가 있을까요?!
try-catch로 Exception까지 처리하고 있는데, SQLException을 throws한 이유가 궁금합니다!

2023-10-08 14:07 UTC, eunbii0213 commented on app/src/main/java/com/techcourse/service/UserService.java
> +    public void changePassword(final long id, final String newPassword, final String createBy) throws SQLException {
사실 어떤 방법을 써도 갈팡질팡.. 둘 다 맘에 들지 않는 갈대같은 저의 마음을 반영한 코드였습니다.. 게다가 final var connection = DataSourceConfig.getInstance().getConnection();를 try안에 넣어버리면 catch문, finally문에서 문제가 생겨서 에잇~! 하고 throw 해버린거였어요..ㅎㅎ헤헷;

이 부분 어떻게 고치는 게 좋을까요??

2023-10-08 14:08 UTC, eunbii0213 commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
> +        System.out.println("로그뜰까요아닐까용오오오");
아니 세상에 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ죄송합니다;;;

2023-10-08 14:08 UTC, eunbii0213 commented on app/src/test/java/com/techcourse/service/MockUserHistoryDao.java
> +        System.out.println("로그뜰까요아닐까용오오오");
으악 창피해 ㅠ

2023-10-09 01:52 UTC, sh111-coder commented on app/src/main/java/com/techcourse/service/UserService.java
> +    public void changePassword(final long id, final String newPassword, final String createBy) throws SQLException {
해당 방식처럼 예외를 throws하면 문제 발생 시에 어디서 발생했는지 추적하기 힘들어질 것 같아요!
그래서 저는 트랜잭션에 관한 예외가 다 해당 메소드에서 처리되니까 해당 메소드 안에서 try-catch를 한번 더 써서
예외를 처리하는 건 어떨까요?!

말씀해주신 부분은 
```suggestion
DataSource dataSource = DataSourceConfig.getInstance();
        Connection connection = null;

        try {
            connection = dataSource.getConnection();
            connection.setAutoCommit(false);

           ...
```

이런 식으로 변경해보면 될 것 같습니다!

2023-10-09 01:54 UTC, sh111-coder approved these changes
질문 드렸던 부분 답변해주셔서 Approve & Merge 할게요!!
재질문 주셨던 부분은 답변에 코멘트 남겨놨습니다!
4단계 진행할 때 참고해서 진행해주시면 될 것 같아요!!

마지막 4단계도 화이팅! 👏👏👏

2023-10-09 01:54 UTC, merged