[JDBC 라이브러리 구현하기 - 3단계] 제이미(임정수) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #526
Opened 2023-10-08 14:09 UTC by JJ503

안녕하세요 그레이!
지난 2단계에서 좋은 리뷰들 감사합니다.

학습테스트와 함께 진행하다 보니 3단계 제출이 늦어졌네요...!
늦어진 제출이 그레이의 일정에 영향이 가지 않길 바랍니다 🥲

이번 리뷰도 잘 부탁드립니다 ☺️

2023-10-09 09:00 UTC, Kim0914 requested changes
안녕하세요 제이미 !

3, 4단계 구현해주신다고 고생많으셨습니다 👍

제이미가 코멘트로 남겨주신 부분 저도 코멘트로 남겼습니다 ㅎㅎ
저도 미션하면서 궁금했던 부분 코멘트로 남겼는데 같이 이야기 나눠봐요 !

2023-10-10 11:35 UTC, JJ503 commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +    final UserHistoryDao userHistoryDao;
누락이 맞습니다...
감사합니다 그레이!

2023-10-10 13:36 UTC, JJ503 commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +        return userDao.findById(id);
저는 `TxUserService`를 트랜잭션을 설정한 서비스라고 이해해서 해당 서비스 클래스 내의 메서드에는 모두 트랜잭션을 설정해 주었습니다..!
크게 고민 없이 트랜잭션이 없는 사용은 `AppUserService`를 통해 진행할 수 있기 때문에 두게 되었습니다.

그렇다면 그레이는 조회 쿼리의 경우 설정해 주셨을까요?
그레이가 최종적으로 내린 결론과 이유가 궁금하네요!

2023-10-10 13:56 UTC, JJ503 commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
> +    public <T> T execute(final TransactionExecuteStrategy<T> executeStrategy) {
감사합니다 그레이..!
덕분에 좀 더 빨리 알아챌 수 있었습니다..!
이전 단계에서 구현했던 `PreparedStatementExecutor`에서 connection을 try-with-resource 방식을 통해 할당했기 때문이었습니다..!
이전 단계 코드라 고려하지 못한 점이 엄청난 삽질이 되었군요 😭

다만 이를 수정하는 과정에서 `PreparedStatementExecutor`와 `TransactionExecutor`가 모두 `DataSourceUti`l의 `releaseConnection`을 통해 커넥션을 할당을 해제하려고 한다면, 그레이가 말씀해 주신 대로 트랜잭션 활성화 여부를 신경 써야 되게 되었습니다.
이를 위해, `releaseConnection`에서 `connection.getAutoCommit()`을 통해 트랜잭션 활성화 여부를 확인해 주기로 했습니다.
또한, `TransactionExecutor`에서 커넥션 할당 해제를 하기 전 커넥션의 autoCommit을 true로 다시 변경시켜주는 과정을 추가했습니다.

혹시 더 좋은 방법이 있다면 공유해주시면 감사하겠습니다!

2023-10-10 16:28 UTC, Kim0914 commented on app/src/main/java/com/techcourse/service/AppUserService.java
> +        return userDao.findById(id);
저는 단건 조회 `findById`의 경우에는 해당 메서드에서 다른 메서드를 호출하지 않기 때문에 트랜잭션을 굳이 설정하지 않았지만, 트랜잭션을 걸지 않을 이유도 없다고 생각이 들더라구요 !

그래서 일관성을 위해서 트랜잭션을 달아주는 방법도 괜찮다고 느꼈습니다 :)

2023-10-10 16:33 UTC, Kim0914 commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionExecutor.java
> +    public <T> T execute(final TransactionExecuteStrategy<T> executeStrategy) {
Connection의 autuCommit을 확인하는 방법을 사용할 수도 있군요 ㅎㅎ

저는 트랜잭션 매니저의 필드에 `isTransactionActivce`라는 필드를 두고 트랜잭션 시작 시 true, 종료 시 false로 설정하는 로직을 추가해 해당 에러를 해결했었습니다 ㅎㅎ

말씀해주신 부분과 일맥상통하는 부분인 것 같아요 !

커넥션 홀더는 저도 크게 필요성을 느끼지 못해서 구현하지 않았습니다...!!
필요하다고 느끼는 순간에 확장하는게 좋지 않을까 싶어요 😎

2023-10-10 16:35 UTC, Kim0914 approved these changes
안녕하세요 제이미 ! 그레이입니다 ㅎㅎ

변경해주신 부분 모두 확인했습니다 👍
커넥션 문제를 빠르게 해결하셨다니 다행이네요 !

이번 미션 너무 고생많으셨고 다음 미션도 파이팅이에요 ~!

2023-10-10 16:35 UTC, merged