[JDBC 라이브러리 구현하기 - 4단계] 밀리(김미성) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #544
Opened 2023-10-08 21:59 UTC by miseongk

안녕하세요 키아라 🤗🤗🤗
드디어 마지막 단계네요..!
그동안 리뷰 해주시느라 고생많으셨어요!! 감사해요 ㅎㅎㅎ

이번 단계는 재밌네요 ㅎㅎ 
Connection 객체가 계속 타고 타고 들어가던게 정말 마음에 안들었었는데, 
ThreadLocal로 해결되니 속이 너무 시원하네요 😌
또 서비스를 추상화하니 실제 비즈니스 로직이 들어간 서비스에 트랜잭션 관련된 코드도 싹 없어졌네요 ㅎㅎ

그럼 마지막 리뷰도 잘 부탁드립니다 🙇‍♀️

2023-10-10 07:36 UTC, kiarakim requested changes
밀리📚 키아라입니다🦁
템플릿 콜백 패턴을 멋드러지게 사용해주셨네요!👍 밀리 코드 너무 멋져요,, 밀리 멋져요.

밀리는 중복을 제거하기 위해 템플릿 콜백 패턴을 사용하셨잖아요, 그런데 changePassword()에서만 적용하고 findById()와 insert() 메서드엔 적용 하지 않은 이유가 궁금합니다!

항상 approve를 드렸는데 그럼 시시하니까 이번엔 request change 드릴게요헿
바꿀건 많이 없을거에욥. 수고하셨습니다~

2023-10-10 08:39 UTC, miseongk commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
두 메서드는 transactionManager의 메서드로 감싸지 않아도 어짜피 jdbcTemplate 단에서 실행되면서 트랜잭션을 타요! 
transactionManager는 setAutoCommit(false)를 설정해주기 위해서 필요한 메서드이고, 만약 단일 쿼리가 실행된다면 jdbcTemplate에서 setAutoCommit(true)로 알아서 트랜잭션이 실행되기 때문이에요!

다만 transactionManager을 거치지 않으면 connection이 닫히지 않고 있는 문제가 있더라구요. 그래서 connectiom의 AutoCommit이 true 이면 connection을 닫아주도록 처리했습니다!

2023-10-10 08:41 UTC, miseongk commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return resources.get().get(key);
없는 경우 null을 반환하기 때문에, null에 대한 처리는 DataSourceUtils에서 try문으로 처리가 되고 있어요!

2023-10-11 04:21 UTC, kiarakim approved these changes
밀리📚 이번 JDBC 미션 정말 수고 많으셨어요.
요구사항을 잘 이해하고 능동적으로 코드를 작성하는 모습이 정말 멋있어요.

이렇다할 리뷰를 남겨드리지 못해 죄송할 뿐인데, 저는 밀리와 함께 하게 되어 영광이었습니다ㅎㅎ
이만 머지 할게요! 다음 미션도 화이팅~!

2023-10-11 04:21 UTC, kiarakim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +    }
오.. 그랬었군용👍 멋져요

2023-10-11 04:21 UTC, merged