[JDBC 라이브러리 구현하기 - 4단계] 라온(문채원) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #571
Opened 2023-10-09 07:17 UTC by mcodnjs

안녕하세요, 오션 🌊🌊!! 
드디어 마지막 4단계네요 .. 길고 길었습니다 ㅋㅋ

미션 요구사항 이외에 추가적으로 _`TransactionCallback`_ 과 _`TransactionTemplate`_ 을 통해 트랜잭션 중복 로직을 제거해주었습니다.
어딘가 부족한 부분이 있는거 같지만 .. 시간이 없어서 리뷰 요청 후에 조금 더 고민해보겠습니다 ㅎㅎ
커밋이 많이 없어서 커밋 단위로 보셔도 좋을거 같아요! 

마지막 4단계도 잘 부탁드립니다 🙇‍♂️
뮤텍스와 세마포어 잘 먹겠습니다 *^^*

2023-10-09 10:49 UTC, donghae-kim requested changes
안녕하세요, 라온 !!  <img src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/86547109/99e3d615-c3f5-40d6-9d00-dfd389e2e56b" width="50" height="50"> <img src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/86547109/99e3d615-c3f5-40d6-9d00-dfd389e2e56b" width="50" height="50">
연휴 마지막날까지 4단계 고생하셨습니다 !

Callback과 Template을 이용해서 로직을 제거해주신 부분은 잘하신 것 같아요! 그와 관련된 커멘트 남겼으니 확인해주시면 감사하겠습니다.
테스트를 꼼꼼하게 잘 작성해주신 것 같아요. 저도 라온처럼 테스트 잘 짜봐야겠네요 ..

몇가지 커멘트 남겨놨는데 확인 부탁드립니다.😀

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionCallback.java
> +@FunctionalInterface
라온이 1단계에서 함수형 인터페이스와 제네릭이 어렵다 했는데 이젠 정말 잘사용하시네요 👍👍

2023-10-09 10:49 UTC, donghae-kim commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +            return null;
null을 반환하게 해야할까요 ?

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
> +    public <T> T execute(final TransactionCallback<T> action) {
이 메소드를 사용하는 changePassword같은 경우에는 Callback으로 값을 반환할 필요가 없지 않을까요 ?

이 부분 때문에 괜히 return null을 메소드 내부에서 추가한 것 같아요 !

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return oldConnection;
라온은 왜 여기서 Connection이 반환 되어야 한다고 생각하나요 ?
반환 값으로 사용하지도 않는데 말이에요! (저도 잘 몰라서 질문합니다)

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +    @Nullable
nullable 할 수 있음을 명시적으로 표시해주었군요 👍
혹시 sonarLint의 힘 ?!

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        final Connection conn = DataSourceUtils.getConnection(dataSource);
connection 재사용 좋아요 !

2023-10-09 10:49 UTC, donghae-kim commented on jdbc/src/test/java/org/springframework/transaction/support/TransactionTemplateTest.java
> +}
테스트를 진짜 잘 작성해주셨네요 리스펙합니다 !!

2023-10-11 04:11 UTC, mcodnjs reviewed
안녕하세요, 오션 🌊
무의미한 null 값을 반환하는 부분만 조금 수정해봤습니다! 
별거 없는데 조금 늦었네요 😅

마지막 리뷰 요청이 될 것 같은데요, 
오션과 티키타카 하면서 많이 배웠고 !! 재밌었습니다 ~~  
전정준씨랑 얼른 잠실에서 볼 수 있었으면 좋겠네요 *^^*
며칠 안남은 테코톡 기대하겠습니다 😊 파이팅하십쇼 !! 

마지막까지 잘 부탁드립니다 🙇‍♂️
감사합니다 ~~

2023-10-11 04:25 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return oldConnection;
저도 그런식으로 이해했습니다! 그렇기에 라온은 다른 생각을 가지고 있나 궁금해서 물어봤었어요 ~ 😀

2023-10-11 04:29 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
> +    public <T> T execute(final TransactionCallback<T> action) {
좋습니다!

2023-10-11 04:30 UTC, donghae-kim commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionTemplate.java
> +    public <T> T execute(final TransactionCallback<T> action) {
`executeWithOutResult(Runnable action)` 메소드를 통해서 전과 다르게 null 값이 제거되고 가독성도 좋아진 것 같아요!

2023-10-11 04:35 UTC, donghae-kim approved these changes
안녕하세요 라온 ! <img src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/86547109/99e3d615-c3f5-40d6-9d00-dfd389e2e56b" width="50" height="50">

바쁜일정에도 4단계 반영 정말 잘해주셨던 것 같아요! 코드 요구사항도 완전 충족해주시고 완벽한것 같습니다!

마지막 리뷰 Approve가 되겠네요.
저도 라온이 꼼꼼하게 잘 작성해준 코드로 더 많이 배울 수 있는 기회였습니다!
JDBC 미션 고생하셨습니다!
레벨5 때 잠실에서 볼 수 있으면 좋겠네요 ^^ ~~근데 전 선릉이 더 가까운데..~~

고생하셨습니다!😀 남은 레벨4도 화이팅입니다!!

2023-10-11 04:37 UTC, donghae-kim commented
큰라온
<img src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/86547109/99e3d615-c3f5-40d6-9d00-dfd389e2e56b" width="200" height="200">
작은라온
<img src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/86547109/99e3d615-c3f5-40d6-9d00-dfd389e2e56b" width="30" height="30">

2023-10-11 04:38 UTC, merged