[JDBC 라이브러리 구현하기 - 4단계] 이리내(성채연) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #588
Opened 2023-10-09 11:15 UTC by hectick

안녕하세요 채채
빨간날이지만 힘내서 코딩을 마저 해보았습니다

3단계때 코멘트 달아주신 부분에 대한 답변은 달아놓았으니 확인해주세용

이번 단계를 진행하면서 모든 요청은 반드시 TxUserService를 거칠 것이라 생각하고 만들었습니다.
왜냐하면 언제는 트랜잭션 없이 바로 AppUserService를 호출하고 언제는 트랜잭션 있게 TxUserService를 호출하고 이것을 현재 코드상으로 어떻게 구분해줄지 모르겠거든요
그래서 jdbcTemplate에는 따로 connection을 close하는 로직을 넣지 않았어요. 어차피 TransactionExecutor가 해줄테니까용ㅎㅎ,..

그럼 리뷰 잘부탁해용😘

2023-10-10 04:54 UTC, chaewon121 requested changes
이리내 안녕하세요~! 이번 미션 어려웠는데 이리내는 잘 구현해주셨군요~! 저도 아직 트렌젝션 커넥션처리 등등에 관해서 이해도가 높지않아서 이리내의 의견이 궁금한 점들이 있어서 코멘트로 남겨두었습니다~! 커넥션을 닫는 로직에 대해서 좀더 의견을 나누고 싶네요~!

2023-10-10 04:54 UTC, chaewon121 commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        final Connection connection = DataSourceUtils.getConnection(dataSource);
만약 트렌젝션 밖에서 해당 함수가 호출이 되었다면 커넥션을 어떻게 닫을 수 있을까요!? 저도 이부분에 대해서 많이 고민해 보았는데요! 만약 트렌젝션이 실행중이라면 닫지 않고, 실행중이 아니라면 커넥션을 닫는 로직에 대해서 이리내의 의견이 궁금합니다!

2023-10-10 06:03 UTC, chaewon121 commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return resources.get().remove(key);
get()의 중복제거에 대해서 이리내는 어떻게 생각하시나요?

2023-10-10 08:31 UTC, hectick commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +    private static final ThreadLocal<Map<DataSource, Connection>> resources = ThreadLocal.withInitial(HashMap::new);
지선생한테 배웠습니다 ㅋ.ㅋ

2023-10-10 08:32 UTC, hectick commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return resources.get().getOrDefault(key, null);
힘내볼게요

2023-10-10 08:34 UTC, hectick commented on jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java
> +        final Connection connection = DataSourceUtils.getConnection(dataSource);
저도 코드리뷰를 하다가 힌트를 좀 얻었는데요
실제로 ConnectionHolder라는 클래스가 존재하더라구요
Connection 객체를 한번 더 감싸준 클래스인데요 필드에 transactionActive가 있어서 이걸 토대로 트랜잭션이 실행중인지 아닌지 판단해서 커넥션을 닫아줄지 말지를 결정할 수 있을 것 같아요
결론은 Connection을 ConnectionHolder로 한번 더 감싸주고 필드에 transactionActive를 추가하는 것!! 입니다.
<img width="703" alt="image" src="https://github.com/woowacourse/jwp-dashboard-jdbc/assets/62106852/5981f499-bbe1-4247-8b84-2615af4d54a4">

2023-10-10 08:38 UTC, hectick commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        return resources.get().remove(key);
get()의 중복 제거가 resources.get()을 따로 메서드로 빼는 것인가요?!
필드가 어떻게 생겼는지 인지를 못했다면 현재 코드를 봤을 때 resources에서 왜 get을 해와서 지우는거지? 생각할 수도 있을 것 같아요
getResources().remove(key) 이러면 더 직관적이고 좋은 것 같슴니다

2023-10-10 08:44 UTC, hectick commented on jdbc/src/main/java/org/springframework/jdbc/datasource/DataSourceUtils.java
> +            TransactionSynchronizationManager.unbindResource(dataSource);
그러게요 생각해보지 못했는데 고민할만한 내용인 것 같습니다
생각해보니 저라면 unbind 해줄 것 같아요
쓰레드가 재사용되는 상황이라면, Connection이 비워지지 않고 남아있으면 위험하지 않을까요??

2023-10-12 16:06 UTC, chaewon121 approved these changes
이리내 안녕하세요~! 학습테스트까지 모두 하시느라 고생 많으셨습니다. 저의 지식을 총동원해서 리뷰를 남겼었는데 모두 적용해주셨네요 ..감동받았구요.. 
이리내의 답변을 보고 저도 힌트를 많이 얻어갈 수 있었네요!
이만 머지하도록 하겠습니다~!

2023-10-12 16:07 UTC, merged