[JDBC 라이브러리 구현하기 - 1단계] 그린론(유재서) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #59
Opened 2022-10-01 16:59 UTC by jaejae-yoo

리버 안녕하세요!
페어 2번에 이어, 이번 미션에서도 뵙네요! 🫢😃 캠퍼스가 달라서 못 뵌 지 꽤 된 것 같아요. 잘 지내시죠 ?!

1단계 요구사항을 만족한 것 같아 리뷰 요청드려요!
궁금한 부분 및 어색한 부분은 편하게 리뷰 남겨주세요!
잘 부탁드려요 👏

2022-10-03 10:13 UTC, gudonghee2000 requested changes
안녕하세요 그린론! 
레벨 1, 2미션에 이어서 이렇게 또 만나게 되어서 정말 반가워요😎

좋은 주말 보내고 계신가요??

작성해주신 코드를 보면서 깔끔하게 구현해주셔서 코드가 잘읽혔어요!
그리고, 꼼꼼하게 작성해주신 테스트코드도 정말 인상깊었습니다ㅎㅎ

그래서 피드백 드릴 부분이 거의 없었지만 
한번 몇가지 피드백을 남겨보았어요!😊

다시한번 리뷰요청 주시면 바로 확인하도록하겠습니다!

2022-10-03 10:13 UTC, gudonghee2000 commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    private JdbcTemplate jdbcTemplate;
안녕하세요 그린론! 
JdbcTemplate과 관련하여 꼼꼼하게 작성해주신 테스트 코드 잘 보았어요!👍👍

저는 JdbcTemplate과 관련하여 `fake` 객체들을 생성하여 테스트를 진행하였는데요!

관리점이 하나더 늘어나고 Connection과 PreparedStatement, ResultSet의 자원해제에 대해서 테스트를 할 방법이 잘 떠오르지 않아 좋은 방법은 아니라는 생각이 들기도하네요..😔

2022-10-04 12:16 UTC, jaejae-yoo commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +
해당 메서드가 실행되었는지 알 수 있어요! 
try-with-resources로 close() 메서드가 실행되었는지 검증하였습니다!

2022-10-04 12:17 UTC, jaejae-yoo commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    }
앗 놓쳤던 부분이네요! 감사합니다. 👍

2022-10-04 12:23 UTC, jaejae-yoo commented on jdbc/src/test/java/nextstep/jdbc/JdbcTemplateTest.java
> +    private JdbcTemplate jdbcTemplate;
Fake 객체를 직접 만드셨군요 👍
실제 동작과 더 유사하게 테스트할 수 있어서 좋은 방법같아요! 공유해주셔서 감사합니다. :)

2022-10-04 12:25 UTC, jaejae-yoo commented
리버 안녕하세요 ~ 
남겨주신 리뷰에 대한 답변 남겼습니다. ㅎㅎ
꼼꼼한 리뷰 감사드려요. 👍👍

2022-10-06 01:37 UTC, gudonghee2000 approved these changes
안녕하세요 그린론! 리뷰가 많이 늦었죠...
수정해주신 부분들 모두 확인하였어요!!

그린론의 코드를 보면서 많이 배울수 있었습니다ㅎㅎ
특히 connection과 preraredStatement 자원해제를 테스트하신 부분이
인상깊었어요!!

간단한 리뷰를 조금 남긴부분이있는데요!
다음 pr에서 적용해주시면 같이 확인하겠습니다😊

다음 pr부터는 빠르게 리뷰 드릴께요!!
다음단계에서 다시만나요~🚀🚀

2022-10-06 01:37 UTC, gudonghee2000 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            return resultSetExtractor.extractData(resultSet);
resultSet 자원이 해제 되는군요!!

2022-10-06 01:37 UTC, gudonghee2000 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            throw new EmptyResultDataAccessException(1);
매개변수에 final 키워드가 누락된것 같아요!

2022-10-06 01:37 UTC, gudonghee2000 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +             final PreparedStatement preparedStatement = connection.prepareStatement(sql)
매개변수에 final 키워드가 누락된것 같아요!

2022-10-06 01:38 UTC, merged