[JDBC 구현하기 - 4단계] 도기(김동호) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #598
Opened 2023-10-10 04:09 UTC by kdkdhoho

안녕하세요 무민! 건강상 이슈로 이제야 4단계 제출합니다..!
무민은 건강하세요 😢

요구사항에 충실하게 구현해보았습니다.
그럼 이번에도 잘 부탁드려요 :)

2023-10-10 13:36 UTC, parkmuhyeun commented on app/src/main/java/com/techcourse/dao/UserHistoryDao.java
>          jdbcTemplate.executeQuery(
여기두!

2023-10-10 13:43 UTC, parkmuhyeun commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        resources.set(resource);
이렇게 되면 원래 있던 map에 덮어 씌우지 않을까요!?

2023-10-10 13:44 UTC, parkmuhyeun commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        }
👍🏻

2023-10-10 13:45 UTC, parkmuhyeun commented on jdbc/src/test/java/org/springframework/transaction/support/TransactionSynchronizationManagerTest.java
> +class TransactionSynchronizationManagerTest {
오우 테스트까지 좋네요 ~

2023-10-10 13:52 UTC, parkmuhyeun commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        DataSource dataSource = DataSourceConfig.getInstance();
DataSource를 생성자 주입으로 받아서 사용하면 h2 jdbc에 종속되지도 않을 것 같고 테스트할 때도 더 용이할거 같아서 좋아보이는데 도기는 어떻게 생각하시나요!?

2023-10-10 13:57 UTC, parkmuhyeun requested changes
RC 요청

2023-10-11 05:18 UTC, kdkdhoho commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        resources.set(resource);
음.. 처음엔 덮어 씌어져도 괜찮겠다 했는데요.
Connection이 덮어 씌어져서 기존 Connection이 날라가면 트랜잭션 유지가 안되는 문제가 생길 것 같아서, 예외를 발생하는 쪽으로 수정하겠습니다!

2023-10-11 05:25 UTC, kdkdhoho commented on app/src/main/java/com/techcourse/service/TxUserService.java
> +        DataSource dataSource = DataSourceConfig.getInstance();
적극 동의합니다! 그 부분은 미처 생각하지 못했네요 👍

2023-10-11 05:33 UTC, kdkdhoho commented
항상 감사합니다 무민 :)
그런데 하나 질문이 생겼어요! `TransactionSynchronizationManager`에서 현재 ThreadLocal의 제네릭 타입으로 `Map<DataSource, Connection`을 받고 있잖아요?
그런데 현재 구조에서는 DataSource가 애플리케이션 통틀어 static 변수로 1개만 사용하고 있기 때문에 'ThreadLocal의 제네릭 타입으로 그냥 Connection만 가지면 안되나?'라고 생각했어요.
어차피 ThreadLocal에 할당하는 자원은 쓰레드별로 다르기도 하고, 현재는 DataSource가 전역변수로 1개이기 때문이죠.

어떤 이유에서 기본으로 제공되는 코드가 `Map<DataSource, Connection`일까요?
단일 스프링 애플리케이션에서 동시에 2개 이상의 DataSource를 사용할 수 있기 때문일까요?

2023-10-12 01:46 UTC, parkmuhyeun approved these changes
안녕하세요 도기! 우선 마지막까지 피드백 반영 감사합니다.

> 어떤 이유에서 기본으로 제공되는 코드가 Map<DataSource, Connection일까요?
단일 스프링 애플리케이션에서 동시에 2개 이상의 DataSource를 사용할 수 있기 때문일까요?

예를 들어, 서로 다른 도메인에서 DB를(mysql, redis) 분리 해서 사용하고 하나의 트랜잭션 안에서 동시에 사용할 일이 생긴다면 동시에 다른 Datasource를 사용해서 작업하기 때문에 TransactionSynchronizationManager를 이용해서 좀 더 편리하게 쓰는 것 같습니다!

4단계까지 너무 고생 많으셨고 다음 미션 드디어 마지막인데요..
정말 마지막인만큼 불태우시고 화이팅하십셔 😎

이번 미션은 여기서 머지하겠습니다!

2023-10-12 01:46 UTC, parkmuhyeun commented on jdbc/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java
> +        }
현재는 없을 때만 map을 생성해서 넣고 있는데 있을 때도 넣어주면 좋을 것 같아요!

2023-10-12 01:46 UTC, merged