[JDBC 라이브러리 구현하기 - 1단계] 봄(장보미) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #68
Opened 2022-10-02 07:27 UTC by JangBomi

안녕하세요 렉스! 🦖🦖🦖🦖

1단계 요구사항은 만족하여 PR 제출합니다!
- [x] UserDatoTest의 모든 테스트 케이스가 통과한다
- [x] UserDao가 아닌 JdbcTemplate 클래스에서 JDBC와 관련된 처리를 담당한다.

JdbcTemplateTest를 작성해보려했는데, 어떤 것을 어떻게 테스트해야할지 감이 안잡히네요ㅠㅠ 렉스는 어떻게 테스트하셨는지 궁금해요.

잘 부탁드립니다! 🌱 🙇‍♀️

2022-10-03 05:09 UTC, Seongwon97 requested changes
안녕하세요 봄 🌿 🌿 🌿
연휴기간에도 미션을 빠르게 구현해주시고 너무 부지런하신 것 같아요!

#### 스프링 JdbcTemplate 코드
저는 개인적으로 이번 4레벨에서는 스프링을 우리 손으로 직접 구현해보는 목적으로 각각의 기능을 구현하는 만큼 스프링의 구현 코드들을 살펴보며 미션을 진행해 보는 것도 좋다고 생각해요!
스프링의 코드를 살펴보며 미션을 진행하다보면 그동안 기계적으로 사용하였던 각각의 메서드들의 동작 원리, 발생시키는 상황별 예외 등 많은 것을 배울 수 있더라고요👍
봄도 스프링 코드를 살펴보며 리펙터링을 하는 시간을 갖으면 많은 도움이 되실 것 같아요🚀

#### 테스트 코드
전반적으로 테스트 코드가 추가된 것이 없는 것 같아요! JdbcTemplate의 경우 저도 테스트를 어떻게 작성해야할지 몰라서 다른 크루들의 코드를 참고하였는데 많은 크루들이 Mocking을 통해 사용한 Resource를 올바르게 반환하는지, 메서드들이 잘 실행되는지 등을 체크한 것 같다라고요!
저도 사실 classicist라서 아직까지 Mock을 사용하는 코드가 과연 얼마나 도움이 되는 테스트 코드일까? 개수만 채우려는 테스트 코드가 아닐까? 등의 생각이 들긴 하지만 `리소스 반환을 올바르게 하는지?`에 대한 테스트 정도는 좋은 것 같더라고요😁
그리고 테스트가 현재는 어려운 상황인데 queryForObject의 반환값이 1개가 맞는지?와 같은 로직들을 분리하게 된다면 해당 부분에 대해서도 테스트를 추가할 수 있을 것 같습니다! (스프링에서도 해당 로직을 `DataAccessUtils` 클래스에서 `static` 메서드인 `nullableSingleResult()`로 분리하여 관리하고 있어요!)

코드를 보고 몇가지 피드백을 남겨봤으니 확인 부탁드려요!
궁금한 점이 있으면 언제든지 DM💬주세요!

2022-10-04 15:23 UTC, JangBomi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
메서드 분리하여 finally 문을 제거했습니다!
렉스가 의도하신대로 메서드 분리를 한걸까요? 😭 try-with-resources 문이 중첩으로 사용되어서 제가 원하는대로 자원이 반환되는지도 확신을 못하겠네요

2022-10-04 15:52 UTC, JangBomi commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            }
해당 부분에 대한 예외 처리를 추가했습니다! 👍 👍

2022-10-04 16:05 UTC, JangBomi commented on app/src/main/java/com/techcourse/dao/UserDao.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
기존에 테스트에서 UserDao()의 생성자에서 DataSource를 받고있길래 그대로 구현해줬어요!
findByAccount에서 테스트 격리 문제가 발생하는 것 같아 UserDao테스트에 JdbcTemplate에 대한 의존성을 추가해주면서 
DataSourceConfig.getInstance()를 불필요하게 두 번 호출하는 것 같아 UserDao의 생성자가 JdbcTemplate을 주입받도록 했습니다!

2022-10-05 02:32 UTC, Seongwon97 approved these changes
안녕하세요 봄🌿
리뷰를 잘 반영해주셨네요!!
이번 단계는 이만 머지하겠습니다!!

추가로 남긴 피드백은 다음 단계에서 반영해주세요!!
다음 단계도 화이팅입니다🚀🚀

2022-10-05 02:32 UTC, Seongwon97 commented on app/src/test/java/com/techcourse/dao/UserDaoTest.java
> +        userDao = new UserDao(jdbcTemplate);
`DataSourceConfig.getInstance()` 메서드로 추출하는 dataSource를 변수로 추출하고 재사용하면 메서드의 호출 횟수를 줄일 수 있을 것 같아요!

2022-10-05 02:32 UTC, Seongwon97 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +        return getSingleResult(results);
query메서드 호출을 통한 중복로직 제거 너무 좋네요👍

2022-10-05 02:32 UTC, Seongwon97 commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +    }
```suggestion
    private <T> List<T> getResult(final PreparedStatement preparedStatement,
                                  final RowMapper<T> rowMapper) throws SQLException {
        try (ResultSet rs = preparedStatement.executeQuery()) {
            List<T> result = new ArrayList<>();
            while (rs.next()) {
                result.add(rowMapper.mapRow(rs, rs.getRow()));
            }
            return result;
        }
    }
```
제가 의도한 `ResultSet`관련 코멘트는 메서드 분리를 통해 `try-resource-finally`를 하는 것은 위와 같이 수정하는 것이었어요!! 

`ResultSet`을 만들어 넘겨주기보다 호출한 메서드에서 `ResultSet`을 만들게 된다면 `try-resource-finally`를 사용할 수 있을 것 같아요👍

2022-10-05 02:32 UTC, merged