[JDBC 라이브러리 구현하기 - 1, 2단계] 영이(최준영) 미션 제출합니다.
woowacourse/jwp-dashboard-jdbc pull request #9
Opened 2021-09-21 04:16 UTC by choijy1705

안녕하세요 라이언 
이번에는 리뷰어로 만나네요 ㅋㅋ
리뷰 잘 부탁드립니다.
@Inject 와 @Repository를 활용하여 의존성을 주입할 수 있도록 구현해봤는데 이 부분이 쉽지 않았네요. 
그리고 JdbcTemplateTest를 어떻게 해야할지 모르겠네여 일단 app 모듈에 있는 필요 클래스들을 그대로 가져와서 테스트 진행하였습니다. 확인해보고 좋은 아이디어 있으면 공유해주세여 
코드를 보면서 이해안되는 부분 있으면 언제든 연락주세요.
리뷰 감사합니다.

2021-09-24 08:53 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetterImpl.java
> +public class PreparedStatementSetterImpl implements PreparedStatementSetter{
요구사항중에
`매번 PreparedStatementSetter 인터페이스를 구현하려니 번거롭다. 가변인자를 사용해서 좀더 편리하게 만들 수 없을까?`
한번 고민해보셨으면 좋겠어요!

2021-09-24 08:54 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +                if (rs != null) {
resultset도 try-with-resources를 사용하는 방법이 있지 않을까요?

2021-09-24 08:55 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/JdbcTemplate.java
> +            PreparedStatement pstmt = conn.prepareStatement(sql);
connection과 preparedstatement 관련된 로직들이 모든 메서드에 중복되는데
템플릿,콜백 패턴을 이용해서 어떻게 고칠수있을지 고민해보아요.

2021-09-24 08:56 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetterImpl.java
> +        }
setObject의 첫번째 인자는 무엇을 뜻하는 걸까요? 왜 1부터 시작해야 하는걸까요?
i+1로 처리했을때 문제는 없을까요?

2021-09-24 08:58 UTC, YounghoonKwon commented on jdbc/src/test/java/nextstep/jdbc/User.java
> +public class User {
app모듈안에 있던 user도메인을 이쪽으로 옮기는게 맞을까요?
제 생각에는 jdbc를 구현하는 것이기 때문에 옮기지 않고 요구사항을 충족시키는것이 맞을듯합니다/!

2021-09-24 09:00 UTC, YounghoonKwon commented on jdbc/src/test/java/nextstep/jdbc/DataSourceConfig.java
> +public class DataSourceConfig {
이부분은 app모듈 안에 있는게 맞는거 같아요.
`"jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;"`
이 설정을 하는것이 사용자라고 생각해요.

2021-09-24 09:01 UTC, YounghoonKwon commented on jdbc/src/test/java/nextstep/jdbc/DatabasePopulatorUtils.java
> +public class DatabasePopulatorUtils {
이부분은 저도 jdbc모듈안에있는것이 맞다고 생각합니다.

2021-09-24 09:01 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetterImpl.java
> +        for (int i=0;i<parameters.length;i++) {
formatting 부탁해요

2021-09-24 09:02 UTC, YounghoonKwon commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
> +    void setValues(PreparedStatement pstmt) throws SQLException;
Checked exception 이 사용중이네요.
`SQLException은 Checked Exception이다. 커스텀 Exception을 추가해서 사용자는 Unchecked Exception이 되도록 변경하자.`

2021-09-24 09:03 UTC, YounghoonKwon requested changes
피드백 남겼어요.
더 궁금하신점 있으면 디엠 주세요~

2021-09-25 01:38 UTC, choijy1705 commented on jdbc/src/main/java/nextstep/jdbc/PreparedStatementSetter.java
> +    void setValues(PreparedStatement pstmt) throws SQLException;
이 부분은 jdbcTemplate execute 부분에서 try catch로 잡아지도록 했슴다.

2021-09-25 01:38 UTC, choijy1705 commented on jdbc/src/test/java/nextstep/jdbc/User.java
> +public class User {
test 고민하다가 옮긴건데 mock으로 test하도록 변경하면서 밑에 관련된 부분들 다 지웠습니다.

2021-09-25 06:04 UTC, merged